CREATE FUNCTION cmd_validate_leadership_coordination() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM actor_actor WHERE actor_id=NEW.leader_actor_id AND campaign_id=NEW.campaign_id) THEN RAISE EXCEPTION 'Leadership coordinator belongs to another campaign'; END IF; RETURN NEW; END $$;
CREATE TRIGGER camp_leadership_coordination_valid BEFORE INSERT ON camp_leadership_coordination FOR EACH ROW EXECUTE FUNCTION cmd_validate_leadership_coordination();
CREATE FUNCTION cmd_validate_leadership_allocation() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE c camp_leadership_coordination%ROWTYPE; BEGIN SELECT * INTO STRICT c FROM camp_leadership_coordination WHERE coordination_id=NEW.coordination_id; IF c.coordination_status<>'active' OR NEW.points>c.pool_points_remaining OR NOT EXISTS(SELECT 1 FROM actor_actor WHERE actor_id=NEW.recipient_actor_id AND campaign_id=c.campaign_id) THEN RAISE EXCEPTION 'Leadership allocation violates pool or campaign scope'; END IF; RETURN NEW; END $$;
CREATE TRIGGER camp_leadership_coordination_allocation_valid BEFORE INSERT ON camp_leadership_coordination_allocation FOR EACH ROW EXECUTE FUNCTION cmd_validate_leadership_allocation();
CREATE FUNCTION cmd_validate_leadership_receipts() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE task cmd_actor_task_receipt%ROWTYPE; allocation camp_leadership_coordination_allocation%ROWTYPE; BEGIN
 IF TG_TABLE_NAME='cmd_leadership_coordination_receipt' THEN SELECT * INTO STRICT task FROM cmd_actor_task_receipt WHERE command_id=NEW.leadership_task_command_id; IF task.actor_id<>NEW.leader_actor_id OR task.effect<>NEW.effect OR task.skill_rule_id<>(SELECT skill_rule_id FROM rule_leadership_coordination LIMIT 1) THEN RAISE EXCEPTION 'Leadership coordination receipt task mismatch'; END IF;
 ELSE SELECT * INTO STRICT allocation FROM camp_leadership_coordination_allocation WHERE allocation_id=NEW.allocation_id; IF allocation.coordination_id<>NEW.coordination_id OR allocation.recipient_actor_id<>NEW.recipient_actor_id OR allocation.points<>NEW.points THEN RAISE EXCEPTION 'Leadership allocation receipt mismatch'; END IF; END IF; RETURN NEW; END $$;
CREATE TRIGGER cmd_leadership_coordination_receipt_valid BEFORE INSERT ON cmd_leadership_coordination_receipt FOR EACH ROW EXECUTE FUNCTION cmd_validate_leadership_receipts();
CREATE TRIGGER cmd_leadership_coordination_allocation_receipt_valid BEFORE INSERT ON cmd_leadership_coordination_allocation_receipt FOR EACH ROW EXECUTE FUNCTION cmd_validate_leadership_receipts();
