CREATE FUNCTION cmd_reject_navigation_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Navigation solutions and receipts are immutable'; END $$;
CREATE TRIGGER journey_navigation_solution_immutable BEFORE UPDATE OR DELETE ON journey_navigation_solution FOR EACH ROW EXECUTE FUNCTION cmd_reject_navigation_mutation();
CREATE TRIGGER cmd_navigation_receipt_immutable BEFORE UPDATE OR DELETE ON cmd_navigation_receipt FOR EACH ROW EXECUTE FUNCTION cmd_reject_navigation_mutation();

CREATE FUNCTION cmd_validate_navigation_solution() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE task cmd_actor_task_receipt%ROWTYPE; mode text; BEGIN SELECT * INTO STRICT task FROM cmd_actor_task_receipt WHERE command_id=NEW.task_command_id; SELECT travel_mode INTO STRICT mode FROM journey_leg WHERE journey_leg_id=NEW.journey_leg_id AND campaign_id=NEW.campaign_id; IF task.actor_id<>NEW.navigator_actor_id OR task.skill_rule_id<>(SELECT skill_rule_id FROM rule_navigation_mechanic) OR task.check_total<>NEW.check_total OR task.effect<>NEW.effect OR task.succeeded<>NEW.succeeded OR (NEW.operation_kind='jump_route' AND mode<>'jump') OR (NEW.operation_kind='normal_course' AND mode='jump') THEN RAISE EXCEPTION 'Navigation solution does not match its task or journey leg'; END IF; RETURN NEW; END $$;
CREATE CONSTRAINT TRIGGER journey_navigation_solution_valid AFTER INSERT ON journey_navigation_solution DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION cmd_validate_navigation_solution();

CREATE FUNCTION cmd_validate_navigation_receipt() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE s journey_navigation_solution%ROWTYPE; BEGIN SELECT * INTO STRICT s FROM journey_navigation_solution WHERE navigation_solution_id=NEW.navigation_solution_id; IF s.source_command_id<>NEW.command_id OR s.journey_leg_id<>NEW.journey_leg_id OR s.navigator_actor_id<>NEW.navigator_actor_id OR s.operation_kind<>NEW.operation_kind OR s.task_command_id<>NEW.task_command_id OR s.check_total<>NEW.check_total OR s.effect<>NEW.effect OR s.succeeded<>NEW.succeeded THEN RAISE EXCEPTION 'Navigation receipt does not match its solution'; END IF; RETURN NEW; END $$;
CREATE CONSTRAINT TRIGGER cmd_navigation_receipt_valid AFTER INSERT ON cmd_navigation_receipt DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION cmd_validate_navigation_receipt();

CREATE FUNCTION journey_require_safe_jump_route() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.navigation_solution_id IS NULL OR NOT EXISTS (SELECT 1 FROM journey_navigation_solution s WHERE s.navigation_solution_id=NEW.navigation_solution_id AND s.journey_leg_id=NEW.journey_leg_id AND s.campaign_id=NEW.campaign_id AND s.operation_kind='jump_route' AND s.succeeded) THEN RAISE EXCEPTION 'A safe Jump attempt requires a successful Navigation route for the same leg'; END IF; RETURN NEW; END $$;
CREATE TRIGGER journey_jump_attempt_route_required BEFORE INSERT OR UPDATE OF navigation_solution_id,journey_leg_id,campaign_id ON journey_jump_attempt FOR EACH ROW EXECUTE FUNCTION journey_require_safe_jump_route();
