INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation)
SELECT a.source_work_id,a.source_artifact_id,'heading','Space Combat > Reactions > Point Defense',CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Space Combat: Point Defense' ELSE 'Cepheus Engine v9.1, Space Combat: Point Defense' END
FROM src_artifact a JOIN src_work w USING(source_work_id) WHERE (w.work_code='cepheus-engine.ogn' AND a.source_uri LIKE '%cepheus-engine-space-combat/') OR (w.work_code='cepheus-engine.github-v9.1' AND a.source_uri='src/book2/space-combat.md') ON CONFLICT DO NOTHING;
WITH p AS (SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description)
SELECT content_package_id,'combat.space.point-defense','Point Defense','combat','approved','Ordered turret-laser checks against incoming missiles or boarders.' FROM p;
CREATE TABLE rule_space_combat_point_defense(rule_id bigint PRIMARY KEY REFERENCES rule_rule(rule_id),skill_rule_id bigint NOT NULL REFERENCES rule_skill(rule_id),difficulty_rule_id bigint NOT NULL REFERENCES rule_difficulty(rule_id),required_weapon_kind text NOT NULL CHECK(required_weapon_kind='laser'),missiles_destroyed_per_success smallint NOT NULL CHECK(missiles_destroyed_per_success=1),cumulative_modifier_per_check smallint NOT NULL CHECK(cumulative_modifier_per_check=-1),continue_until_failure boolean NOT NULL,may_change_missile_target boolean NOT NULL,boarding_parties_allowed boolean NOT NULL);
INSERT INTO rule_space_combat_point_defense SELECT r.rule_id,s.rule_id,d.rule_id,'laser',1,-1,true,true,true FROM rule_rule r CROSS JOIN rule_rule s CROSS JOIN rule_rule d WHERE r.rule_code='combat.space.point-defense' AND s.rule_code='skill.turret-weapons' AND d.rule_code='difficulty.average';
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT r.rule_id,r.content_package_id,l.source_locator_id,CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,w.work_code='cepheus-engine.ogn' FROM rule_rule r CROSS JOIN src_locator l JOIN src_work w USING(source_work_id) WHERE r.rule_code='combat.space.point-defense' AND l.heading_path='Space Combat > Reactions > Point Defense' AND w.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');
CREATE TABLE senc_point_defense_sequence(point_defense_sequence_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,reaction_id bigint NOT NULL UNIQUE REFERENCES senc_reaction(reaction_id),missile_salvo_id bigint NOT NULL REFERENCES senc_missile_salvo(missile_salvo_id),engagement_id bigint NOT NULL,campaign_id bigint NOT NULL,space_combat_round_id bigint NOT NULL,senc_vessel_id bigint NOT NULL,gunner_assignment_id bigint NOT NULL,gunner_ship_id bigint NOT NULL,laser_weapon_rule_id bigint NOT NULL REFERENCES ship_weapon_definition(weapon_rule_id),missiles_before smallint NOT NULL CHECK(missiles_before>0),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(space_combat_round_id,engagement_id,campaign_id) REFERENCES senc_round(space_combat_round_id,engagement_id,campaign_id),FOREIGN KEY(senc_vessel_id,engagement_id,campaign_id) REFERENCES senc_vessel(senc_vessel_id,engagement_id,campaign_id),FOREIGN KEY(gunner_assignment_id,gunner_ship_id,campaign_id) REFERENCES ship_crew_assignment(crew_assignment_id,ship_id,campaign_id));
CREATE TABLE senc_point_defense_check_receipt(point_defense_sequence_id bigint NOT NULL REFERENCES senc_point_defense_sequence(point_defense_sequence_id),check_order smallint NOT NULL CHECK(check_order>0),task_command_id bigint NOT NULL UNIQUE REFERENCES cmd_actor_task_receipt(command_id),cumulative_modifier smallint NOT NULL,task_effect smallint NOT NULL,task_succeeded boolean NOT NULL,missiles_before smallint NOT NULL CHECK(missiles_before>0),missiles_after smallint NOT NULL CHECK(missiles_after>=0),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(point_defense_sequence_id,check_order),CHECK(cumulative_modifier=-(check_order-1)),CHECK(missiles_after=missiles_before-CASE WHEN task_succeeded THEN 1 ELSE 0 END));
CREATE FUNCTION senc_validate_point_defense_sequence() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE rr record; salvo senc_missile_salvo%ROWTYPE; installed_kind text; class_id bigint; BEGIN
 SELECT trigger_action.space_combat_round_id,trigger_action.target_vessel_id,reacting_action.action_code,turn.senc_vessel_id,turn.crew_assignment_id,assignment.ship_id,assignment.duty_status,definition.position_code INTO rr FROM senc_reaction reaction JOIN senc_action trigger_action ON trigger_action.space_combat_action_id=reaction.triggering_action_id JOIN senc_action reacting_action ON reacting_action.space_combat_action_id=reaction.reacting_action_id JOIN senc_crew_turn turn ON turn.crew_turn_id=reacting_action.crew_turn_id JOIN ship_crew_assignment assignment USING(crew_assignment_id) JOIN ship_crew_position ps USING(ship_crew_position_id) JOIN ship_crew_position_definition definition USING(crew_position_rule_id) WHERE reaction.reaction_id=NEW.reaction_id;
 SELECT * INTO STRICT salvo FROM senc_missile_salvo WHERE missile_salvo_id=NEW.missile_salvo_id FOR UPDATE; SELECT weapon_kind INTO installed_kind FROM ship_weapon_definition WHERE weapon_rule_id=NEW.laser_weapon_rule_id; SELECT ship_class_rule_id INTO class_id FROM ship_ship WHERE ship_id=NEW.gunner_ship_id;
 IF rr.action_code<>'point-defense' OR rr.space_combat_round_id<>NEW.space_combat_round_id OR rr.target_vessel_id<>NEW.senc_vessel_id OR rr.senc_vessel_id<>NEW.senc_vessel_id OR rr.crew_assignment_id<>NEW.gunner_assignment_id OR rr.ship_id<>NEW.gunner_ship_id OR rr.duty_status<>'active' OR rr.position_code<>'gunner' OR salvo.target_vessel_id<>NEW.senc_vessel_id OR salvo.missiles_remaining<>NEW.missiles_before OR installed_kind<>'laser' OR NOT EXISTS(SELECT 1 FROM ship_class_weapon WHERE ship_class_rule_id=class_id AND weapon_rule_id=NEW.laser_weapon_rule_id) THEN RAISE EXCEPTION 'Point Defense requires matching incoming salvo, active Gunner, and installed turret laser' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER senc_point_defense_sequence_valid BEFORE INSERT ON senc_point_defense_sequence FOR EACH ROW EXECUTE FUNCTION senc_validate_point_defense_sequence();
CREATE FUNCTION senc_apply_point_defense_check() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE seq senc_point_defense_sequence%ROWTYPE; task record; actor bigint; skill bigint; average bigint; current_missiles integer; BEGIN
 SELECT * INTO STRICT seq FROM senc_point_defense_sequence WHERE point_defense_sequence_id=NEW.point_defense_sequence_id FOR UPDATE; IF EXISTS(SELECT 1 FROM senc_point_defense_check_receipt WHERE point_defense_sequence_id=NEW.point_defense_sequence_id AND NOT task_succeeded) THEN RAISE EXCEPTION 'Point Defense sequence ended at its first failed check' USING ERRCODE='23514'; END IF;
 SELECT assignment.actor_id INTO actor FROM ship_crew_assignment assignment WHERE crew_assignment_id=seq.gunner_assignment_id; SELECT actor_id,skill_rule_id,difficulty_rule_id,circumstance_modifier,effect,succeeded INTO task FROM cmd_actor_task_receipt WHERE command_id=NEW.task_command_id; SELECT rule_id INTO skill FROM rule_rule WHERE rule_code='skill.turret-weapons'; SELECT rule_id INTO average FROM rule_rule WHERE rule_code='difficulty.average'; SELECT missiles_remaining INTO current_missiles FROM senc_missile_salvo WHERE missile_salvo_id=seq.missile_salvo_id FOR UPDATE;
 IF NEW.check_order<>(SELECT count(*)+1 FROM senc_point_defense_check_receipt WHERE point_defense_sequence_id=NEW.point_defense_sequence_id) OR task.actor_id<>actor OR task.skill_rule_id<>skill OR task.difficulty_rule_id<>average OR task.circumstance_modifier<>NEW.cumulative_modifier OR task.effect<>NEW.task_effect OR task.succeeded<>NEW.task_succeeded OR current_missiles<>NEW.missiles_before THEN RAISE EXCEPTION 'Point Defense check sequence or task is inconsistent' USING ERRCODE='23514'; END IF;
 UPDATE senc_missile_salvo SET missiles_remaining=NEW.missiles_after,salvo_status=CASE WHEN NEW.missiles_after=0 THEN 'destroyed' ELSE salvo_status END WHERE missile_salvo_id=seq.missile_salvo_id; RETURN NEW; END $$;
CREATE TRIGGER senc_point_defense_check_valid BEFORE INSERT ON senc_point_defense_check_receipt FOR EACH ROW EXECUTE FUNCTION senc_apply_point_defense_check();
CREATE FUNCTION senc_reject_point_defense_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Point Defense receipts are immutable'; END $$;
CREATE TRIGGER senc_point_defense_sequence_immutable BEFORE UPDATE OR DELETE ON senc_point_defense_sequence FOR EACH ROW EXECUTE FUNCTION senc_reject_point_defense_mutation(); CREATE TRIGGER senc_point_defense_check_immutable BEFORE UPDATE OR DELETE ON senc_point_defense_check_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_point_defense_mutation();
