INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation) SELECT a.source_work_id,a.source_artifact_id,'heading','Space Combat > Reactions > Trigger Screens',CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Space Combat: Trigger Screens' ELSE 'Cepheus Engine v9.1, Space Combat: Trigger Screens' END FROM src_artifact a JOIN src_work w USING(source_work_id) WHERE (w.work_code='cepheus-engine.ogn' AND a.source_uri LIKE '%cepheus-engine-space-combat/') OR (w.work_code='cepheus-engine.github-v9.1' AND a.source_uri='src/book2/space-combat.md') ON CONFLICT DO NOTHING;
WITH p AS (SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description) SELECT content_package_id,'combat.space.trigger-screens','Trigger Screens','combat','approved','Skilled commander or gunner activates a compatible installed screen against incoming fire.' FROM p;
CREATE TABLE rule_space_combat_trigger_screens(rule_id bigint PRIMARY KEY REFERENCES rule_rule(rule_id),skill_rule_id bigint NOT NULL REFERENCES rule_skill(rule_id),minimum_skill_level smallint NOT NULL CHECK(minimum_skill_level=0),damage_reduction_dice smallint NOT NULL CHECK(damage_reduction_dice=2),damage_reduction_die_sides smallint NOT NULL CHECK(damage_reduction_die_sides=6),add_operator_skill boolean NOT NULL,nuclear_removes_automatic_radiation boolean NOT NULL,commander_or_gunner_may_operate boolean NOT NULL);
INSERT INTO rule_space_combat_trigger_screens SELECT r.rule_id,s.rule_id,0,2,6,true,true,true FROM rule_rule r CROSS JOIN rule_rule s WHERE r.rule_code='combat.space.trigger-screens' AND s.rule_code='skill.screens';
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT r.rule_id,r.content_package_id,l.source_locator_id,CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,w.work_code='cepheus-engine.ogn' FROM rule_rule r CROSS JOIN src_locator l JOIN src_work w USING(source_work_id) WHERE r.rule_code='combat.space.trigger-screens' AND l.heading_path='Space Combat > Reactions > Trigger Screens' AND w.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');
CREATE TABLE senc_screen_attempt_receipt(screen_attempt_receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,reaction_id bigint NOT NULL UNIQUE REFERENCES senc_reaction(reaction_id),engagement_id bigint NOT NULL,campaign_id bigint NOT NULL,space_combat_round_id bigint NOT NULL,senc_vessel_id bigint NOT NULL,operator_assignment_id bigint NOT NULL,operator_ship_id bigint NOT NULL,screen_code text NOT NULL REFERENCES rule_ship_screen(screen_code),incoming_weapon_kind text NOT NULL CHECK(incoming_weapon_kind IN('meson','fusion','nuclear-missile')),operator_skill_level smallint NOT NULL CHECK(operator_skill_level>=0),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(space_combat_round_id,engagement_id,campaign_id) REFERENCES senc_round(space_combat_round_id,engagement_id,campaign_id),FOREIGN KEY(senc_vessel_id,engagement_id,campaign_id) REFERENCES senc_vessel(senc_vessel_id,engagement_id,campaign_id),FOREIGN KEY(operator_assignment_id,operator_ship_id,campaign_id) REFERENCES ship_crew_assignment(crew_assignment_id,ship_id,campaign_id));
CREATE TABLE senc_screen_reduction_die(screen_attempt_receipt_id bigint NOT NULL REFERENCES senc_screen_attempt_receipt(screen_attempt_receipt_id),die_order smallint NOT NULL CHECK(die_order BETWEEN 1 AND 2),result smallint NOT NULL CHECK(result BETWEEN 1 AND 6),PRIMARY KEY(screen_attempt_receipt_id,die_order));
CREATE TABLE senc_screen_final_receipt(screen_attempt_receipt_id bigint PRIMARY KEY REFERENCES senc_screen_attempt_receipt(screen_attempt_receipt_id),rolled_reduction smallint NOT NULL CHECK(rolled_reduction BETWEEN 2 AND 12),total_damage_reduction smallint NOT NULL CHECK(total_damage_reduction>=2),automatic_radiation_removed boolean NOT NULL,recorded_at timestamptz NOT NULL DEFAULT clock_timestamp());
CREATE FUNCTION senc_validate_screen_attempt() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE rr record; actor bigint; skill bigint; level integer; class_id bigint; protected text; BEGIN
 SELECT trigger_action.space_combat_round_id,trigger_action.target_vessel_id,attack.weapon_rule_id,reacting_action.action_code,turn.senc_vessel_id,turn.crew_assignment_id,assignment.ship_id,assignment.actor_id,assignment.duty_status,definition.position_code INTO rr FROM senc_reaction reaction JOIN senc_action trigger_action ON trigger_action.space_combat_action_id=reaction.triggering_action_id JOIN senc_attack attack ON attack.space_combat_action_id=trigger_action.space_combat_action_id JOIN senc_action reacting_action ON reacting_action.space_combat_action_id=reaction.reacting_action_id JOIN senc_crew_turn turn ON turn.crew_turn_id=reacting_action.crew_turn_id JOIN ship_crew_assignment assignment USING(crew_assignment_id) JOIN ship_crew_position ps USING(ship_crew_position_id) JOIN ship_crew_position_definition definition USING(crew_position_rule_id) WHERE reaction.reaction_id=NEW.reaction_id;
 SELECT rule_id INTO skill FROM rule_rule WHERE rule_code='skill.screens'; SELECT skill_level INTO level FROM actor_skill WHERE actor_id=rr.actor_id AND skill_rule_id=skill; SELECT ship_class_rule_id INTO class_id FROM ship_ship WHERE ship_id=NEW.operator_ship_id; SELECT protected_weapon_kind INTO protected FROM rule_ship_screen WHERE screen_code=NEW.screen_code;
 IF rr.action_code<>'trigger-screens' OR rr.space_combat_round_id<>NEW.space_combat_round_id OR rr.target_vessel_id<>NEW.senc_vessel_id OR rr.senc_vessel_id<>NEW.senc_vessel_id OR rr.crew_assignment_id<>NEW.operator_assignment_id OR rr.ship_id<>NEW.operator_ship_id OR rr.duty_status<>'active' OR rr.position_code NOT IN('master','gunner') OR level IS NULL OR level<>NEW.operator_skill_level OR NOT EXISTS(SELECT 1 FROM ship_class_screen WHERE ship_class_rule_id=class_id AND screen_code=NEW.screen_code) OR NOT ((protected='meson' AND NEW.incoming_weapon_kind='meson') OR (protected='fusion_and_nuclear' AND NEW.incoming_weapon_kind IN('fusion','nuclear-missile'))) OR (NEW.incoming_weapon_kind<>'nuclear-missile' AND (SELECT weapon_kind FROM ship_weapon_definition WHERE weapon_rule_id=rr.weapon_rule_id)<>NEW.incoming_weapon_kind) THEN RAISE EXCEPTION 'Trigger Screens requires compatible installed screen and trained commander or gunner' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER senc_screen_attempt_valid BEFORE INSERT ON senc_screen_attempt_receipt FOR EACH ROW EXECUTE FUNCTION senc_validate_screen_attempt();
CREATE FUNCTION senc_guard_screen_die() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF EXISTS(SELECT 1 FROM senc_screen_final_receipt WHERE screen_attempt_receipt_id=NEW.screen_attempt_receipt_id) THEN RAISE EXCEPTION 'Screen reduction dice cannot follow finalization' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER senc_screen_die_valid BEFORE INSERT ON senc_screen_reduction_die FOR EACH ROW EXECUTE FUNCTION senc_guard_screen_die();
CREATE FUNCTION senc_validate_screen_final() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE a senc_screen_attempt_receipt%ROWTYPE; n integer; total integer; BEGIN SELECT * INTO STRICT a FROM senc_screen_attempt_receipt WHERE screen_attempt_receipt_id=NEW.screen_attempt_receipt_id FOR UPDATE; SELECT count(*),coalesce(sum(result),0) INTO n,total FROM senc_screen_reduction_die WHERE screen_attempt_receipt_id=NEW.screen_attempt_receipt_id; IF n<>2 OR total<>NEW.rolled_reduction OR NEW.total_damage_reduction<>total+a.operator_skill_level OR NEW.automatic_radiation_removed<>(a.screen_code='nuclear-damper' AND a.incoming_weapon_kind='nuclear-missile') THEN RAISE EXCEPTION 'Screen final receipt fails dice, skill, or radiation recomputation' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;
CREATE TRIGGER senc_screen_final_valid BEFORE INSERT ON senc_screen_final_receipt FOR EACH ROW EXECUTE FUNCTION senc_validate_screen_final();
CREATE FUNCTION senc_reject_screen_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Screen receipts and dice are immutable'; END $$; CREATE TRIGGER senc_screen_attempt_immutable BEFORE UPDATE OR DELETE ON senc_screen_attempt_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_screen_mutation(); CREATE TRIGGER senc_screen_die_immutable BEFORE UPDATE OR DELETE ON senc_screen_reduction_die FOR EACH ROW EXECUTE FUNCTION senc_reject_screen_mutation(); CREATE TRIGGER senc_screen_final_immutable BEFORE UPDATE OR DELETE ON senc_screen_final_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_screen_mutation();
