INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation)
SELECT a.source_work_id,a.source_artifact_id,'heading','Space Combat > Special Considerations > Abstract Boarding Rules',
 CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Space Combat: Abstract Boarding Rules' ELSE 'Cepheus Engine v9.1, Space Combat: Abstract Boarding Rules' END
FROM src_artifact a JOIN src_work w USING(source_work_id) WHERE (w.work_code='cepheus-engine.ogn' AND a.source_uri LIKE '%cepheus-engine-space-combat/') OR (w.work_code='cepheus-engine.github-v9.1' AND a.source_uri='src/book2/space-combat.md') ON CONFLICT DO NOTHING;
WITH p AS(SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description)
SELECT content_package_id,'combat.space.abstract-boarding','Abstract Boarding','combat','approved','Round-by-round opposed Intelligence/Tactics boarding resolution with persistent control, reaction, modifier, and internal-damage consequences.' FROM p;
CREATE TABLE rule_space_combat_abstract_boarding(rule_id bigint PRIMARY KEY REFERENCES rule_rule(rule_id),skill_rule_id bigint NOT NULL REFERENCES rule_skill(rule_id),characteristic_rule_id bigint NOT NULL REFERENCES rule_characteristic(rule_id),exceptional_effect_minimum smallint NOT NULL CHECK(exceptional_effect_minimum=6),success_next_check_dm smallint NOT NULL CHECK(success_next_check_dm=2),attacker_success_denies_defender_reactions boolean NOT NULL,success_internal_single_hits smallint NOT NULL CHECK(success_internal_single_hits=1),exceptional_internal_damage_dice smallint NOT NULL CHECK(exceptional_internal_damage_dice=2),exceptional_internal_damage_die_sides smallint NOT NULL CHECK(exceptional_internal_damage_die_sides=6),control_delay_turns smallint NOT NULL CHECK(control_delay_turns=1),requires_docked_range boolean NOT NULL);
INSERT INTO rule_space_combat_abstract_boarding SELECT b.rule_id,s.rule_id,c.rule_id,6,2,true,1,2,6,1,true FROM rule_rule b CROSS JOIN rule_rule s CROSS JOIN rule_rule c WHERE b.rule_code='combat.space.abstract-boarding' AND s.rule_code='skill.tactics' AND c.rule_code='characteristic.intelligence';
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT r.rule_id,r.content_package_id,l.source_locator_id,CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,w.work_code='cepheus-engine.ogn' FROM rule_rule r CROSS JOIN src_locator l JOIN src_work w USING(source_work_id) WHERE r.rule_code='combat.space.abstract-boarding' AND l.heading_path='Space Combat > Special Considerations > Abstract Boarding Rules' AND w.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');

CREATE TABLE senc_boarding_operation(boarding_operation_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,engagement_id bigint NOT NULL,campaign_id bigint NOT NULL,attacker_vessel_id bigint NOT NULL,defender_vessel_id bigint NOT NULL,operation_status text NOT NULL DEFAULT 'active' CHECK(operation_status IN('active','attacker-control-pending','attacker-controlled','attacker-repelled')),control_available_round integer,concurrency_version bigint NOT NULL DEFAULT 1 CHECK(concurrency_version>0),opened_at timestamptz NOT NULL DEFAULT clock_timestamp(),closed_at timestamptz,FOREIGN KEY(attacker_vessel_id,engagement_id,campaign_id) REFERENCES senc_vessel(senc_vessel_id,engagement_id,campaign_id),FOREIGN KEY(defender_vessel_id,engagement_id,campaign_id) REFERENCES senc_vessel(senc_vessel_id,engagement_id,campaign_id),UNIQUE(engagement_id,attacker_vessel_id,defender_vessel_id),CHECK(attacker_vessel_id<>defender_vessel_id),CHECK((operation_status='active')=(closed_at IS NULL)),CHECK((operation_status='attacker-control-pending')=(control_available_round IS NOT NULL)));
CREATE TABLE senc_boarding_round_receipt(boarding_round_receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,boarding_operation_id bigint NOT NULL REFERENCES senc_boarding_operation(boarding_operation_id),space_combat_round_id bigint NOT NULL,engagement_id bigint NOT NULL,campaign_id bigint NOT NULL,round_number integer NOT NULL CHECK(round_number>0),action_id bigint NOT NULL UNIQUE,attacker_assignment_id bigint NOT NULL,defender_assignment_id bigint NOT NULL,attacker_task_command_id bigint NOT NULL UNIQUE REFERENCES cmd_actor_task_receipt(command_id),defender_task_command_id bigint NOT NULL UNIQUE REFERENCES cmd_actor_task_receipt(command_id),attacker_effect smallint NOT NULL,defender_effect smallint NOT NULL,attacker_intelligence smallint NOT NULL,defender_intelligence smallint NOT NULL,winner text NOT NULL CHECK(winner IN('attacker','defender','tie')),success_degree text NOT NULL CHECK(success_degree IN('success','exceptional-success','reroll-required')),attacker_next_dm smallint NOT NULL,defender_next_dm smallint NOT NULL,defender_reactions_denied boolean NOT NULL,resulting_status text NOT NULL CHECK(resulting_status IN('active','attacker-control-pending','attacker-repelled')),damage_mode text NOT NULL CHECK(damage_mode IN('none','single-internal-hit','2d6-internal-damage')),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(space_combat_round_id,engagement_id,campaign_id) REFERENCES senc_round(space_combat_round_id,engagement_id,campaign_id),FOREIGN KEY(action_id,engagement_id,campaign_id) REFERENCES senc_action(space_combat_action_id,engagement_id,campaign_id),UNIQUE(boarding_operation_id,round_number));
CREATE TABLE senc_boarding_internal_damage_die(boarding_round_receipt_id bigint NOT NULL REFERENCES senc_boarding_round_receipt(boarding_round_receipt_id),die_order smallint NOT NULL CHECK(die_order BETWEEN 1 AND 2),result smallint NOT NULL CHECK(result BETWEEN 1 AND 6),PRIMARY KEY(boarding_round_receipt_id,die_order));
CREATE TABLE senc_boarding_internal_damage_receipt(boarding_round_receipt_id bigint PRIMARY KEY REFERENCES senc_boarding_round_receipt(boarding_round_receipt_id),target_ship_id bigint NOT NULL,campaign_id bigint NOT NULL,rolled_damage smallint NOT NULL CHECK(rolled_damage>0),single_hit_groups smallint NOT NULL CHECK(single_hit_groups>=0),double_hit_groups smallint NOT NULL CHECK(double_hit_groups>=0),triple_hit_groups smallint NOT NULL CHECK(triple_hit_groups>=0),damage_status text NOT NULL DEFAULT 'queued' CHECK(damage_status IN('queued','applied')),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(target_ship_id,campaign_id) REFERENCES ship_ship(ship_id,campaign_id));
CREATE TABLE senc_boarding_reaction_denial(boarding_round_receipt_id bigint PRIMARY KEY REFERENCES senc_boarding_round_receipt(boarding_round_receipt_id),space_combat_round_id bigint NOT NULL,senc_vessel_id bigint NOT NULL,denied boolean NOT NULL CHECK(denied),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp());

CREATE FUNCTION senc_validate_boarding_round() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE op senc_boarding_operation%ROWTYPE;a record;atask cmd_actor_task_receipt%ROWTYPE;dtask cmd_actor_task_receipt%ROWTYPE;expected_winner text;expected_degree text;expected_status text;expected_damage text;range_code text;tactics bigint;intel bigint;BEGIN
 SELECT * INTO STRICT op FROM senc_boarding_operation WHERE boarding_operation_id=NEW.boarding_operation_id FOR UPDATE;
 SELECT action.action_code,action.target_vessel_id,action.space_combat_round_id,turn.senc_vessel_id,turn.crew_assignment_id INTO STRICT a FROM senc_action action JOIN senc_crew_turn turn USING(crew_turn_id) WHERE action.space_combat_action_id=NEW.action_id;
 SELECT * INTO STRICT atask FROM cmd_actor_task_receipt WHERE command_id=NEW.attacker_task_command_id;SELECT * INTO STRICT dtask FROM cmd_actor_task_receipt WHERE command_id=NEW.defender_task_command_id;
 SELECT rule_id INTO STRICT tactics FROM rule_rule WHERE rule_code='skill.tactics';SELECT rule_id INTO STRICT intel FROM rule_rule WHERE rule_code='characteristic.intelligence';
 SELECT range_band_code INTO STRICT range_code FROM senc_vessel_range WHERE engagement_id=NEW.engagement_id AND first_vessel_id=least(op.attacker_vessel_id,op.defender_vessel_id) AND second_vessel_id=greatest(op.attacker_vessel_id,op.defender_vessel_id);
 expected_winner:=CASE WHEN NEW.attacker_effect>NEW.defender_effect THEN 'attacker' WHEN NEW.attacker_effect<NEW.defender_effect THEN 'defender' WHEN NEW.attacker_intelligence>NEW.defender_intelligence THEN 'attacker' WHEN NEW.attacker_intelligence<NEW.defender_intelligence THEN 'defender' ELSE 'tie' END;
 expected_degree:=CASE WHEN expected_winner='tie' THEN 'reroll-required' WHEN greatest(NEW.attacker_effect,NEW.defender_effect)>=6 THEN 'exceptional-success' ELSE 'success' END;
 expected_status:=CASE WHEN expected_winner='attacker' AND expected_degree='exceptional-success' THEN 'attacker-control-pending' WHEN expected_winner='defender' AND expected_degree='exceptional-success' THEN 'attacker-repelled' ELSE 'active' END;
 expected_damage:=CASE WHEN expected_winner='attacker' AND expected_degree='exceptional-success' THEN '2d6-internal-damage' WHEN expected_degree='success' THEN 'single-internal-hit' ELSE 'none' END;
 IF op.operation_status<>'active' OR op.engagement_id<>NEW.engagement_id OR op.campaign_id<>NEW.campaign_id OR a.action_code<>'boarding-action' OR a.target_vessel_id<>op.defender_vessel_id OR a.senc_vessel_id<>op.attacker_vessel_id OR a.space_combat_round_id<>NEW.space_combat_round_id OR a.crew_assignment_id<>NEW.attacker_assignment_id OR range_code<>'docked'
  OR NOT EXISTS(SELECT 1 FROM senc_crew_role_assignment WHERE engagement_id=NEW.engagement_id AND senc_vessel_id=op.attacker_vessel_id AND crew_assignment_id=NEW.attacker_assignment_id AND crew_role IN('security_or_marine','captain') AND ended_at IS NULL)
  OR NOT EXISTS(SELECT 1 FROM senc_crew_role_assignment WHERE engagement_id=NEW.engagement_id AND senc_vessel_id=op.defender_vessel_id AND crew_assignment_id=NEW.defender_assignment_id AND crew_role IN('security_or_marine','captain') AND ended_at IS NULL)
  OR atask.skill_rule_id<>tactics OR dtask.skill_rule_id<>tactics OR atask.characteristic_rule_id<>intel OR dtask.characteristic_rule_id<>intel OR atask.effect<>NEW.attacker_effect OR dtask.effect<>NEW.defender_effect
  OR NEW.winner<>expected_winner OR NEW.success_degree<>expected_degree OR NEW.resulting_status<>expected_status OR NEW.damage_mode<>expected_damage
  OR NEW.attacker_next_dm<>(CASE WHEN expected_winner='attacker' AND expected_degree='success' THEN 2 ELSE 0 END) OR NEW.defender_next_dm<>(CASE WHEN expected_winner='defender' AND expected_degree='success' THEN 2 ELSE 0 END)
  OR NEW.defender_reactions_denied<>(expected_winner='attacker' AND expected_degree='success') THEN RAISE EXCEPTION 'Abstract boarding round fails docked roles, opposed Intelligence/Tactics checks, or published outcome recomputation' USING ERRCODE='23514';END IF;
 IF expected_status<>'active' THEN UPDATE senc_boarding_operation SET operation_status=expected_status,control_available_round=CASE WHEN expected_status='attacker-control-pending' THEN NEW.round_number+1 END,closed_at=clock_timestamp(),concurrency_version=concurrency_version+1 WHERE boarding_operation_id=op.boarding_operation_id;END IF;
 RETURN NEW;END $$;
CREATE TRIGGER senc_boarding_round_valid BEFORE INSERT ON senc_boarding_round_receipt FOR EACH ROW EXECUTE FUNCTION senc_validate_boarding_round();
CREATE FUNCTION senc_record_boarding_reaction_denial() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE defender bigint;BEGIN IF NEW.defender_reactions_denied THEN SELECT defender_vessel_id INTO STRICT defender FROM senc_boarding_operation WHERE boarding_operation_id=NEW.boarding_operation_id;INSERT INTO senc_boarding_reaction_denial(boarding_round_receipt_id,space_combat_round_id,senc_vessel_id,denied) VALUES(NEW.boarding_round_receipt_id,NEW.space_combat_round_id,defender,true);END IF;RETURN NEW;END $$;
CREATE TRIGGER senc_boarding_round_denial AFTER INSERT ON senc_boarding_round_receipt FOR EACH ROW EXECUTE FUNCTION senc_record_boarding_reaction_denial();
CREATE FUNCTION senc_validate_boarding_damage() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE r senc_boarding_round_receipt%ROWTYPE;target bigint;n integer;total integer;singles integer;doubles integer;triples integer;BEGIN SELECT * INTO STRICT r FROM senc_boarding_round_receipt WHERE boarding_round_receipt_id=NEW.boarding_round_receipt_id FOR UPDATE;SELECT vessel.ship_id INTO STRICT target FROM senc_boarding_operation op JOIN senc_vessel vessel ON vessel.senc_vessel_id=op.defender_vessel_id WHERE op.boarding_operation_id=r.boarding_operation_id;SELECT count(*),coalesce(sum(result),0) INTO n,total FROM senc_boarding_internal_damage_die WHERE boarding_round_receipt_id=NEW.boarding_round_receipt_id;
 IF r.damage_mode='single-internal-hit' THEN singles:=1;doubles:=0;triples:=0;total:=1;ELSIF r.damage_mode='2d6-internal-damage' THEN SELECT single_hit_groups,double_hit_groups,triple_hit_groups INTO singles,doubles,triples FROM rule_space_combat_damage_band WHERE damage_range @> total;ELSE RAISE EXCEPTION 'Boarding round has no internal damage';END IF;
 IF NEW.target_ship_id<>target OR NEW.campaign_id<>r.campaign_id OR n<>(CASE WHEN r.damage_mode='2d6-internal-damage' THEN 2 ELSE 0 END) OR NEW.rolled_damage<>total OR NEW.single_hit_groups<>singles OR NEW.double_hit_groups<>doubles OR NEW.triple_hit_groups<>triples THEN RAISE EXCEPTION 'Boarding internal damage fails published outcome and dice recomputation' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER senc_boarding_damage_valid BEFORE INSERT ON senc_boarding_internal_damage_receipt FOR EACH ROW EXECUTE FUNCTION senc_validate_boarding_damage();
CREATE FUNCTION senc_reject_boarding_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Abstract boarding receipts are immutable';END $$;
CREATE TRIGGER senc_boarding_round_immutable BEFORE UPDATE OR DELETE ON senc_boarding_round_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_mutation();CREATE TRIGGER senc_boarding_die_immutable BEFORE UPDATE OR DELETE ON senc_boarding_internal_damage_die FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_mutation();CREATE TRIGGER senc_boarding_damage_immutable BEFORE UPDATE OR DELETE ON senc_boarding_internal_damage_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_mutation();CREATE TRIGGER senc_boarding_denial_immutable BEFORE UPDATE OR DELETE ON senc_boarding_reaction_denial FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_mutation();
