CREATE FUNCTION senc_enforce_boarding_reaction_denial() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE vessel bigint;round_id bigint;BEGIN SELECT turn.senc_vessel_id,action.space_combat_round_id INTO vessel,round_id FROM senc_action action JOIN senc_crew_turn turn USING(crew_turn_id) WHERE action.space_combat_action_id=NEW.reacting_action_id;IF EXISTS(SELECT 1 FROM senc_boarding_reaction_denial WHERE space_combat_round_id=round_id AND senc_vessel_id=vessel AND denied) THEN RAISE EXCEPTION 'Successful attacking boarders deny defender reactions this round' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER senc_boarding_reaction_denial_enforced BEFORE INSERT ON senc_reaction FOR EACH ROW EXECUTE FUNCTION senc_enforce_boarding_reaction_denial();

CREATE TABLE senc_boarding_damage_location_group_roll(boarding_round_receipt_id bigint NOT NULL REFERENCES senc_boarding_internal_damage_receipt(boarding_round_receipt_id),group_order smallint NOT NULL CHECK(group_order>0),hit_multiplicity smallint NOT NULL CHECK(hit_multiplicity BETWEEN 1 AND 3),first_die smallint NOT NULL CHECK(first_die BETWEEN 1 AND 6),second_die smallint NOT NULL CHECK(second_die BETWEEN 1 AND 6),roll_total smallint NOT NULL CHECK(roll_total=first_die+second_die),PRIMARY KEY(boarding_round_receipt_id,group_order));
CREATE TABLE senc_boarding_damage_location_hit_receipt(boarding_damage_location_hit_receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,boarding_round_receipt_id bigint NOT NULL,group_order smallint NOT NULL,hit_order smallint NOT NULL CHECK(hit_order BETWEEN 1 AND 3),target_ship_id bigint NOT NULL,campaign_id bigint NOT NULL,rolled_location text NOT NULL,applied_location text NOT NULL,effect_code text NOT NULL,hull_before smallint NOT NULL,hull_after smallint NOT NULL,structure_before smallint NOT NULL,structure_after smallint NOT NULL,armor_before smallint NOT NULL,armor_after smallint NOT NULL,ship_version_before bigint NOT NULL,ship_version_after bigint NOT NULL CHECK(ship_version_after=ship_version_before+1),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(boarding_round_receipt_id,group_order,hit_order),FOREIGN KEY(boarding_round_receipt_id,group_order) REFERENCES senc_boarding_damage_location_group_roll(boarding_round_receipt_id,group_order),FOREIGN KEY(target_ship_id,campaign_id) REFERENCES ship_ship(ship_id,campaign_id));
CREATE FUNCTION senc_validate_boarding_location_group() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE d senc_boarding_internal_damage_receipt%ROWTYPE;existing integer;BEGIN SELECT * INTO STRICT d FROM senc_boarding_internal_damage_receipt WHERE boarding_round_receipt_id=NEW.boarding_round_receipt_id FOR UPDATE;SELECT count(*) INTO existing FROM senc_boarding_damage_location_group_roll WHERE boarding_round_receipt_id=NEW.boarding_round_receipt_id AND hit_multiplicity=NEW.hit_multiplicity;IF d.damage_status<>'queued' OR existing>=(CASE NEW.hit_multiplicity WHEN 1 THEN d.single_hit_groups WHEN 2 THEN d.double_hit_groups ELSE d.triple_hit_groups END) OR NEW.group_order<>(SELECT count(*)+1 FROM senc_boarding_damage_location_group_roll WHERE boarding_round_receipt_id=NEW.boarding_round_receipt_id) THEN RAISE EXCEPTION 'Boarding internal location group exceeds its damage-band sequence' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER senc_boarding_location_group_valid BEFORE INSERT ON senc_boarding_damage_location_group_roll FOR EACH ROW EXECUTE FUNCTION senc_validate_boarding_location_group();
CREATE FUNCTION senc_apply_next_boarding_location_hit(p_round bigint) RETURNS bigint LANGUAGE plpgsql AS $$ DECLARE d senc_boarding_internal_damage_receipt%ROWTYPE;g record;s ship_ship%ROWTYPE;loc rule_space_combat_hit_location%ROWTYPE;grp smallint;hitno smallint;rolled text;applied text;effect text;rid bigint;remaining integer;state_before smallint;state_after smallint;overflow text;status text;attack_dm smallint:=0;sensor_dm smallint:=0;BEGIN
 SELECT * INTO STRICT d FROM senc_boarding_internal_damage_receipt WHERE boarding_round_receipt_id=p_round FOR UPDATE;SELECT groups.group_order,count(h.boarding_damage_location_hit_receipt_id)::smallint+1 INTO grp,hitno FROM senc_boarding_damage_location_group_roll groups LEFT JOIN senc_boarding_damage_location_hit_receipt h USING(boarding_round_receipt_id,group_order) WHERE groups.boarding_round_receipt_id=p_round GROUP BY groups.group_order,groups.hit_multiplicity HAVING count(h.boarding_damage_location_hit_receipt_id)<groups.hit_multiplicity ORDER BY groups.group_order LIMIT 1;IF grp IS NULL THEN RAISE EXCEPTION 'All boarding internal hits are applied';END IF;
 SELECT * INTO STRICT g FROM senc_boarding_damage_location_group_roll WHERE boarding_round_receipt_id=p_round AND group_order=grp;SELECT * INTO STRICT s FROM ship_ship WHERE ship_id=d.target_ship_id FOR UPDATE;SELECT * INTO STRICT loc FROM rule_space_combat_hit_location WHERE roll_total=g.roll_total;rolled:=loc.internal_vessel_location;applied:=rolled;
 IF applied IN('bay','j-drive','power-plant','bridge','hold') THEN SELECT hit_count INTO state_before FROM senc_ship_system_damage_state WHERE ship_id=s.ship_id AND system_code=applied AND system_instance=1 FOR UPDATE;state_before:=coalesce(state_before,0);IF state_before>=3 THEN SELECT overflow_location_code INTO STRICT overflow FROM rule_space_combat_location_effect e JOIN rule_rule r ON r.rule_id=e.hit_location_rule_id WHERE r.rule_code='combat.space.hit-locations' AND location_code=applied AND hit_ordinal=4;applied:=overflow;state_after:=state_before;ELSE state_after:=state_before+1;SELECT effect_code,attack_dm,sensor_dm INTO STRICT effect,attack_dm,sensor_dm FROM rule_space_combat_location_effect e JOIN rule_rule r ON r.rule_id=e.hit_location_rule_id WHERE r.rule_code='combat.space.hit-locations' AND location_code=applied AND hit_ordinal=state_after;END IF;END IF;
 IF effect IS NULL THEN effect:=CASE applied WHEN 'structure' THEN 'reduce-structure' WHEN 'crew' THEN 'roll-crew-damage' ELSE 'system-hit' END;END IF;
 UPDATE ship_ship SET structure_current=CASE WHEN applied='structure' THEN greatest(0,structure_current-1) ELSE structure_current END,concurrency_version=concurrency_version+1,lifecycle_status=CASE WHEN applied='structure' AND structure_current<=1 THEN 'destroyed' ELSE lifecycle_status END,ended_at=CASE WHEN applied='structure' AND structure_current<=1 THEN coalesce(ended_at,clock_timestamp()) ELSE ended_at END WHERE ship_id=s.ship_id;
 IF state_before IS NOT NULL AND state_after>state_before THEN status:=CASE state_after WHEN 1 THEN 'damaged' WHEN 2 THEN 'disabled' ELSE 'destroyed' END;INSERT INTO senc_ship_system_damage_state(ship_id,campaign_id,system_code,system_instance,hit_count,system_status,attack_dm,sensor_dm) VALUES(s.ship_id,s.campaign_id,rolled,1,state_after,status,attack_dm,sensor_dm) ON CONFLICT(ship_id,system_code,system_instance) DO UPDATE SET hit_count=EXCLUDED.hit_count,system_status=EXCLUDED.system_status,attack_dm=CASE WHEN EXCLUDED.hit_count=1 THEN EXCLUDED.attack_dm ELSE senc_ship_system_damage_state.attack_dm END,sensor_dm=CASE WHEN EXCLUDED.hit_count=1 THEN EXCLUDED.sensor_dm ELSE senc_ship_system_damage_state.sensor_dm END,concurrency_version=senc_ship_system_damage_state.concurrency_version+1,updated_at=clock_timestamp();END IF;
 INSERT INTO senc_boarding_damage_location_hit_receipt(boarding_round_receipt_id,group_order,hit_order,target_ship_id,campaign_id,rolled_location,applied_location,effect_code,hull_before,hull_after,structure_before,structure_after,armor_before,armor_after,ship_version_before,ship_version_after) VALUES(p_round,grp,hitno,s.ship_id,s.campaign_id,rolled,applied,effect,s.hull_current,s.hull_current,s.structure_current,CASE WHEN applied='structure' THEN greatest(0,s.structure_current-1) ELSE s.structure_current END,s.armor_current,s.armor_current,s.concurrency_version,s.concurrency_version+1) RETURNING boarding_damage_location_hit_receipt_id INTO rid;
 SELECT sum(hit_multiplicity)-count(h.boarding_damage_location_hit_receipt_id) INTO remaining FROM senc_boarding_damage_location_group_roll groups LEFT JOIN senc_boarding_damage_location_hit_receipt h USING(boarding_round_receipt_id,group_order) WHERE groups.boarding_round_receipt_id=p_round;IF remaining=0 THEN UPDATE senc_boarding_internal_damage_receipt SET damage_status='applied' WHERE boarding_round_receipt_id=p_round;END IF;RETURN rid;END $$;
CREATE FUNCTION senc_reject_boarding_location_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Boarding location rolls and hit receipts are immutable';END $$;CREATE TRIGGER senc_boarding_location_group_immutable BEFORE UPDATE OR DELETE ON senc_boarding_damage_location_group_roll FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_location_mutation();CREATE TRIGGER senc_boarding_location_hit_immutable BEFORE UPDATE OR DELETE ON senc_boarding_damage_location_hit_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_boarding_location_mutation();
CREATE OR REPLACE FUNCTION senc_reject_boarding_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_TABLE_NAME='senc_boarding_internal_damage_receipt' AND TG_OP='UPDATE' AND OLD.damage_status='queued' AND NEW.damage_status='applied' AND (to_jsonb(OLD)-'damage_status')=(to_jsonb(NEW)-'damage_status') THEN RETURN NEW;END IF;RAISE EXCEPTION 'Abstract boarding receipts are immutable';END $$;
