INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation) SELECT a.source_work_id,a.source_artifact_id,'heading','Space Combat > Special Considerations > Special Weapon Rules',CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Space Combat: Special Weapon Rules' ELSE 'Cepheus Engine v9.1, Space Combat: Special Weapon Rules' END FROM src_artifact a JOIN src_work w USING(source_work_id) WHERE (w.work_code='cepheus-engine.ogn' AND a.source_uri LIKE '%cepheus-engine-space-combat/') OR (w.work_code='cepheus-engine.github-v9.1' AND a.source_uri='src/book2/space-combat.md') ON CONFLICT DO NOTHING;
WITH p AS(SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description) SELECT content_package_id,'combat.space.special-weapons','Space Combat Special Weapons','combat','approved','Meson, fusion, particle, nuclear, and offensive sandcaster special damage behavior.' FROM p;
CREATE TABLE rule_space_combat_special_weapon(rule_id bigint NOT NULL REFERENCES rule_rule(rule_id),weapon_rule_id bigint NOT NULL REFERENCES ship_weapon_definition(weapon_rule_id),force_internal_damage boolean NOT NULL,ignore_armor boolean NOT NULL,additional_radiation_crew_hit boolean NOT NULL,radiation_armor_dm boolean NOT NULL,offensive_fixed_damage smallint,offensive_maximum_range text REFERENCES rule_space_range_band(range_band_code),PRIMARY KEY(rule_id,weapon_rule_id),CHECK((offensive_fixed_damage IS NULL)=(offensive_maximum_range IS NULL)));
INSERT INTO rule_space_combat_special_weapon SELECT r.rule_id,w.weapon_rule_id,w.weapon_kind='meson',w.weapon_kind='meson',w.weapon_kind IN('meson','fusion','particle'),w.weapon_kind IN('fusion','particle'),CASE WHEN w.weapon_kind='sandcaster' THEN 1 END,CASE WHEN w.weapon_kind='sandcaster' THEN 'close' END FROM rule_rule r CROSS JOIN ship_weapon_definition w WHERE r.rule_code='combat.space.special-weapons' AND w.weapon_kind IN('meson','fusion','particle','sandcaster');
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT r.rule_id,r.content_package_id,l.source_locator_id,CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,w.work_code='cepheus-engine.ogn' FROM rule_rule r CROSS JOIN src_locator l JOIN src_work w USING(source_work_id) WHERE r.rule_code='combat.space.special-weapons' AND l.heading_path='Space Combat > Special Considerations > Special Weapon Rules' AND w.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');

CREATE TABLE senc_special_weapon_radiation_hit_receipt(mount_weapon_attack_check_id bigint PRIMARY KEY REFERENCES senc_mount_weapon_attack_check(mount_weapon_attack_check_id),target_ship_id bigint NOT NULL,campaign_id bigint NOT NULL,weapon_rule_id bigint NOT NULL REFERENCES ship_weapon_definition(weapon_rule_id),armor_snapshot smallint NOT NULL CHECK(armor_snapshot>=0),armor_dm smallint NOT NULL CHECK(armor_dm<=0),die_one smallint NOT NULL CHECK(die_one BETWEEN 1 AND 6),die_two smallint NOT NULL CHECK(die_two BETWEEN 1 AND 6),unmodified_roll smallint NOT NULL CHECK(unmodified_roll=die_one+die_two),modified_roll smallint NOT NULL CHECK(modified_roll=unmodified_roll+armor_dm),target_scope text NOT NULL CHECK(target_scope IN('none','one-random','all')),damage_dice_count smallint NOT NULL CHECK(damage_dice_count IN(0,2,4)),outcome_code text NOT NULL,recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),FOREIGN KEY(target_ship_id,campaign_id) REFERENCES ship_ship(ship_id,campaign_id));
CREATE FUNCTION senc_validate_special_weapon_radiation() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE attack record;special rule_space_combat_special_weapon%ROWTYPE;target record;expected record;bounded integer;BEGIN SELECT check_row.hit,check_row.weapon_rule_id,declaration.campaign_id,declaration.target_vessel_id INTO STRICT attack FROM senc_mount_weapon_attack_check check_row JOIN senc_mount_attack_declaration declaration USING(mount_attack_declaration_id) WHERE check_row.mount_weapon_attack_check_id=NEW.mount_weapon_attack_check_id;SELECT special_row.* INTO STRICT special FROM rule_space_combat_special_weapon special_row JOIN rule_rule r ON r.rule_id=special_row.rule_id WHERE r.rule_code='combat.space.special-weapons' AND special_row.weapon_rule_id=attack.weapon_rule_id;SELECT ship.ship_id,ship.armor_current INTO STRICT target FROM senc_vessel vessel JOIN ship_ship ship USING(ship_id) WHERE vessel.senc_vessel_id=attack.target_vessel_id;bounded:=greatest(2,least(12,NEW.modified_roll));SELECT band.* INTO STRICT expected FROM rule_space_combat_crew_damage_band band JOIN rule_rule r ON r.rule_id=band.hit_location_rule_id WHERE r.rule_code='combat.space.hit-locations' AND band.damage_kind='radiation' AND band.roll_range @> bounded;
 IF NOT attack.hit OR NOT special.additional_radiation_crew_hit OR NEW.weapon_rule_id<>attack.weapon_rule_id OR NEW.target_ship_id<>target.ship_id OR NEW.campaign_id<>attack.campaign_id OR NEW.armor_snapshot<>target.armor_current OR NEW.armor_dm<>(CASE WHEN special.radiation_armor_dm THEN -target.armor_current ELSE 0 END) OR NEW.target_scope<>expected.target_scope OR NEW.damage_dice_count<>expected.damage_dice_count OR NEW.outcome_code<>expected.outcome_code THEN RAISE EXCEPTION 'Special-weapon radiation hit must match its confirmed hit, armor rule, dice, and published crew outcome' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER senc_special_weapon_radiation_valid BEFORE INSERT ON senc_special_weapon_radiation_hit_receipt FOR EACH ROW EXECUTE FUNCTION senc_validate_special_weapon_radiation();

ALTER TABLE senc_missile_crew_hit_receipt ADD COLUMN special_weapon_attack_check_id bigint UNIQUE REFERENCES senc_special_weapon_radiation_hit_receipt(mount_weapon_attack_check_id);
ALTER TABLE senc_missile_crew_hit_receipt DROP CONSTRAINT senc_missile_crew_hit_receipt_check2,ADD CONSTRAINT senc_crew_hit_one_space_weapon_origin CHECK(num_nonnulls(missile_damage_location_hit_receipt_id,nuclear_missile_impact_attempt_id,special_weapon_attack_check_id)=1);
CREATE OR REPLACE FUNCTION senc_validate_missile_crew_hit() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE origin record;crew_count integer;expected record;bounded integer;BEGIN
 IF NEW.missile_damage_location_hit_receipt_id IS NOT NULL THEN SELECT target_ship_id,campaign_id,'normal'::text AS kind,0::smallint AS armor_dm INTO STRICT origin FROM senc_missile_damage_location_hit_receipt WHERE missile_damage_location_hit_receipt_id=NEW.missile_damage_location_hit_receipt_id AND effect_code='roll-crew-damage';
 ELSIF NEW.nuclear_missile_impact_attempt_id IS NOT NULL THEN SELECT target_ship_id,campaign_id,'radiation'::text AS kind,armor_dm,die_one,die_two,unmodified_roll,modified_roll,target_scope,damage_dice_count,outcome_code INTO STRICT origin FROM senc_nuclear_missile_radiation_hit_receipt WHERE missile_impact_attempt_id=NEW.nuclear_missile_impact_attempt_id AND missile_order=NEW.nuclear_missile_order;
 ELSE SELECT target_ship_id,campaign_id,'radiation'::text AS kind,armor_dm,die_one,die_two,unmodified_roll,modified_roll,target_scope,damage_dice_count,outcome_code INTO STRICT origin FROM senc_special_weapon_radiation_hit_receipt WHERE mount_weapon_attack_check_id=NEW.special_weapon_attack_check_id;END IF;
 SELECT count(*) INTO crew_count FROM ship_crew_assignment WHERE ship_id=origin.target_ship_id AND campaign_id=origin.campaign_id AND duty_status='active';bounded:=greatest(2,least(12,NEW.modified_roll));SELECT band.* INTO STRICT expected FROM rule_space_combat_crew_damage_band band JOIN rule_rule r ON r.rule_id=band.hit_location_rule_id WHERE r.rule_code='combat.space.hit-locations' AND band.damage_kind=origin.kind AND band.roll_range @> bounded;
 IF NEW.target_ship_id<>origin.target_ship_id OR NEW.campaign_id<>origin.campaign_id OR NEW.damage_kind<>origin.kind OR NEW.active_crew_count<>crew_count OR crew_count=0 OR NEW.armor_dm<>origin.armor_dm OR ((NEW.nuclear_missile_impact_attempt_id IS NOT NULL OR NEW.special_weapon_attack_check_id IS NOT NULL) AND (NEW.die_one<>origin.die_one OR NEW.die_two<>origin.die_two OR NEW.unmodified_roll<>origin.unmodified_roll OR NEW.modified_roll<>origin.modified_roll)) OR NEW.target_scope<>expected.target_scope OR NEW.damage_dice_count<>expected.damage_dice_count OR NEW.damage_die_sides IS DISTINCT FROM expected.damage_die_sides OR NEW.radiation_multiplier_rads IS DISTINCT FROM expected.radiation_multiplier_rads OR NEW.outcome_code<>expected.outcome_code THEN RAISE EXCEPTION 'Space-weapon crew hit must match its source, active crew snapshot, dice, armor DM, and published outcome band' USING ERRCODE='23514';END IF;RETURN NEW;END $$;

ALTER TABLE senc_damage_location_group_roll ADD COLUMN forced_internal boolean NOT NULL DEFAULT false;
CREATE OR REPLACE FUNCTION senc_validate_damage_location_group_roll() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE final senc_mount_damage_final_receipt%ROWTYPE;existing integer;expected_internal boolean;BEGIN SELECT * INTO STRICT final FROM senc_mount_damage_final_receipt WHERE mount_attack_declaration_id=NEW.mount_attack_declaration_id FOR UPDATE;IF final.damage_status<>'queued' OR EXISTS(SELECT 1 FROM senc_damage_location_roll_set_receipt WHERE mount_attack_declaration_id=NEW.mount_attack_declaration_id) THEN RAISE EXCEPTION 'Damage location groups require queued, unfinalized mount damage' USING ERRCODE='23514';END IF;SELECT bool_and(profile.weapon_profile_code='meson-gun') INTO expected_internal FROM senc_mount_weapon_attack_check check_row JOIN rule_space_combat_weapon_profile profile USING(weapon_rule_id) WHERE check_row.mount_attack_declaration_id=NEW.mount_attack_declaration_id AND check_row.hit;SELECT count(*) INTO existing FROM senc_damage_location_group_roll WHERE mount_attack_declaration_id=NEW.mount_attack_declaration_id AND hit_multiplicity=NEW.hit_multiplicity;IF NEW.forced_internal<>coalesce(expected_internal,false) OR existing>=(CASE NEW.hit_multiplicity WHEN 1 THEN final.single_hit_groups WHEN 2 THEN final.double_hit_groups ELSE final.triple_hit_groups END) OR NEW.group_order<>(SELECT count(*)+1 FROM senc_damage_location_group_roll WHERE mount_attack_declaration_id=NEW.mount_attack_declaration_id) THEN RAISE EXCEPTION 'Damage location group exceeds its sequence or special routing rule' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE FUNCTION senc_reject_special_weapon_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Special weapon radiation receipts are immutable';END $$;CREATE TRIGGER senc_special_weapon_radiation_immutable BEFORE UPDATE OR DELETE ON senc_special_weapon_radiation_hit_receipt FOR EACH ROW EXECUTE FUNCTION senc_reject_special_weapon_mutation();
