CREATE TABLE env_deprivation_episode(
 deprivation_episode_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,actor_id bigint NOT NULL,campaign_id bigint NOT NULL,
 deprivation_profile_id bigint NOT NULL REFERENCES rule_deprivation_profile(deprivation_profile_id),endurance_snapshot smallint NOT NULL CHECK(endurance_snapshot>=0),
 began_campaign_day bigint NOT NULL,began_campaign_second integer NOT NULL CHECK(began_campaign_second BETWEEN 0 AND 86399),first_check_due_total_seconds bigint NOT NULL,
 next_check_due_total_seconds bigint NOT NULL,checks_completed integer NOT NULL DEFAULT 0 CHECK(checks_completed>=0),episode_status text NOT NULL DEFAULT 'active' CHECK(episode_status IN('active','relieved')),
 concurrency_version bigint NOT NULL DEFAULT 1 CHECK(concurrency_version>0),opened_at timestamptz NOT NULL DEFAULT clock_timestamp(),relieved_at timestamptz,
 FOREIGN KEY(actor_id,campaign_id) REFERENCES actor_actor(actor_id,campaign_id),CHECK((episode_status='active')=(relieved_at IS NULL))
);
CREATE UNIQUE INDEX env_one_active_deprivation_kind ON env_deprivation_episode(actor_id,deprivation_profile_id) WHERE episode_status='active';
CREATE TABLE env_deprivation_relief_receipt(
 deprivation_relief_receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,deprivation_episode_id bigint NOT NULL UNIQUE REFERENCES env_deprivation_episode(deprivation_episode_id),
 campaign_day bigint NOT NULL,campaign_second integer NOT NULL CHECK(campaign_second BETWEEN 0 AND 86399),requirement_quantity numeric(8,2) NOT NULL CHECK(requirement_quantity>0),requirement_unit text NOT NULL,
 episode_version_before bigint NOT NULL,episode_version_after bigint NOT NULL CHECK(episode_version_after=episode_version_before+1),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE TABLE env_deprivation_check_receipt(
 deprivation_check_receipt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,deprivation_episode_id bigint NOT NULL REFERENCES env_deprivation_episode(deprivation_episode_id),
 check_sequence integer NOT NULL CHECK(check_sequence>0),task_command_id bigint NOT NULL UNIQUE REFERENCES cmd_actor_task_receipt(command_id),campaign_day bigint NOT NULL,campaign_second integer NOT NULL CHECK(campaign_second BETWEEN 0 AND 86399),
 cumulative_previous_check_dm smallint NOT NULL,task_succeeded boolean NOT NULL,damage_die_result smallint CHECK(damage_die_result BETWEEN 1 AND 6),rolled_damage smallint NOT NULL CHECK(rolled_damage>=0),
 episode_version_before bigint NOT NULL,episode_version_after bigint NOT NULL CHECK(episode_version_after=episode_version_before+1),recorded_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(deprivation_episode_id,check_sequence),
 CHECK((task_succeeded AND damage_die_result IS NULL AND rolled_damage=0) OR (NOT task_succeeded AND damage_die_result IS NOT NULL AND rolled_damage=damage_die_result))
);
ALTER TABLE health_damage_instance ADD COLUMN deprivation_check_receipt_id bigint UNIQUE REFERENCES env_deprivation_check_receipt(deprivation_check_receipt_id) DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE health_damage_instance DROP CONSTRAINT health_damage_exactly_one_source_check,
 ADD CONSTRAINT health_damage_exactly_one_source_check CHECK(num_nonnulls(attack_command_id,environmental_command_id,explosion_command_id,grapple_option_command_id,personal_scale_attack_receipt_id,acid_damage_attempt_id,acid_fume_task_command_id,temperature_damage_receipt_id,fire_resolution_receipt_id,fall_attempt_id,poison_attempt_id,radiation_sickness_check_receipt_id,deprivation_check_receipt_id)+CASE WHEN crew_damage_location_hit_receipt_id IS NULL THEN 0 ELSE 1 END+CASE WHEN missile_crew_hit_receipt_id IS NULL THEN 0 ELSE 1 END=1);
CREATE TABLE health_deprivation_recovery_lock(
 damage_instance_id bigint PRIMARY KEY REFERENCES health_damage_instance(damage_instance_id),deprivation_episode_id bigint NOT NULL REFERENCES env_deprivation_episode(deprivation_episode_id),
 deprivation_check_receipt_id bigint NOT NULL UNIQUE REFERENCES env_deprivation_check_receipt(deprivation_check_receipt_id),released_by_relief_receipt_id bigint REFERENCES env_deprivation_relief_receipt(deprivation_relief_receipt_id),
 locked_at timestamptz NOT NULL DEFAULT clock_timestamp(),released_at timestamptz,CHECK((released_by_relief_receipt_id IS NULL)=(released_at IS NULL))
);
CREATE FUNCTION env_validate_deprivation_episode() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE profile rule_deprivation_profile%ROWTYPE;endurance smallint;start_total bigint;expected_due bigint;BEGIN
 SELECT * INTO STRICT profile FROM rule_deprivation_profile WHERE deprivation_profile_id=NEW.deprivation_profile_id;SELECT characteristic.current_value INTO STRICT endurance FROM actor_characteristic characteristic JOIN rule_rule rule ON rule.rule_id=characteristic.characteristic_rule_id WHERE characteristic.actor_id=NEW.actor_id AND rule.rule_code='characteristic.endurance';
 start_total:=NEW.began_campaign_day*86400+NEW.began_campaign_second;expected_due:=start_total+profile.grace_base_seconds+endurance*profile.grace_endurance_seconds;
 IF NEW.endurance_snapshot<>endurance OR NEW.first_check_due_total_seconds<>expected_due OR NEW.next_check_due_total_seconds<>expected_due THEN RAISE EXCEPTION 'Deprivation episode must snapshot current Endurance and published grace period' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER env_deprivation_episode_valid BEFORE INSERT ON env_deprivation_episode FOR EACH ROW EXECUTE FUNCTION env_validate_deprivation_episode();
CREATE FUNCTION env_finalize_deprivation_check() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE episode env_deprivation_episode%ROWTYPE;profile rule_deprivation_profile%ROWTYPE;task cmd_actor_task_receipt%ROWTYPE;now_total bigint;damage_id bigint;BEGIN
 SELECT * INTO STRICT episode FROM env_deprivation_episode WHERE deprivation_episode_id=NEW.deprivation_episode_id FOR UPDATE;SELECT * INTO STRICT profile FROM rule_deprivation_profile WHERE deprivation_profile_id=episode.deprivation_profile_id;SELECT * INTO STRICT task FROM cmd_actor_task_receipt WHERE command_id=NEW.task_command_id;now_total:=NEW.campaign_day*86400+NEW.campaign_second;
 IF episode.episode_status<>'active' OR now_total<episode.next_check_due_total_seconds OR NEW.check_sequence<>episode.checks_completed+1 OR NEW.episode_version_before<>episode.concurrency_version
  OR task.actor_id<>episode.actor_id OR task.characteristic_rule_id<>(SELECT rule_id FROM rule_rule WHERE rule_code='characteristic.endurance') OR task.skill_rule_id IS NOT NULL OR task.difficulty_rule_id<>profile.difficulty_rule_id
  OR NEW.cumulative_previous_check_dm<>(NEW.check_sequence-1)*profile.previous_check_dm_step OR task.circumstance_modifier<>NEW.cumulative_previous_check_dm OR NEW.task_succeeded<>task.succeeded THEN RAISE EXCEPTION 'Deprivation check must match active episode timing, sequence, Routine Endurance task, cumulative DM, result, and version' USING ERRCODE='23514';END IF;
 IF NOT NEW.task_succeeded THEN INSERT INTO health_damage_instance(target_actor_id,penetrating_damage,deprivation_check_receipt_id) VALUES(episode.actor_id,NEW.rolled_damage,NEW.deprivation_check_receipt_id) RETURNING damage_instance_id INTO damage_id;INSERT INTO health_deprivation_recovery_lock(damage_instance_id,deprivation_episode_id,deprivation_check_receipt_id) VALUES(damage_id,episode.deprivation_episode_id,NEW.deprivation_check_receipt_id);END IF;
 UPDATE env_deprivation_episode SET checks_completed=NEW.check_sequence,next_check_due_total_seconds=now_total+profile.check_interval_seconds,concurrency_version=NEW.episode_version_after WHERE deprivation_episode_id=episode.deprivation_episode_id;RETURN NEW;END $$;
CREATE TRIGGER env_deprivation_check_final BEFORE INSERT ON env_deprivation_check_receipt FOR EACH ROW EXECUTE FUNCTION env_finalize_deprivation_check();
CREATE FUNCTION env_finalize_deprivation_relief() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE episode env_deprivation_episode%ROWTYPE;profile rule_deprivation_profile%ROWTYPE;now_total bigint;BEGIN SELECT * INTO STRICT episode FROM env_deprivation_episode WHERE deprivation_episode_id=NEW.deprivation_episode_id FOR UPDATE;SELECT * INTO STRICT profile FROM rule_deprivation_profile WHERE deprivation_profile_id=episode.deprivation_profile_id;now_total:=NEW.campaign_day*86400+NEW.campaign_second;
 IF episode.episode_status<>'active' OR now_total<episode.began_campaign_day*86400+episode.began_campaign_second OR NEW.requirement_quantity<profile.normal_daily_requirement OR NEW.requirement_unit<>profile.requirement_unit OR NEW.episode_version_before<>episode.concurrency_version THEN RAISE EXCEPTION 'Deprivation relief must meet the published requirement and active episode version' USING ERRCODE='23514';END IF;
 UPDATE env_deprivation_episode SET episode_status='relieved',relieved_at=NEW.recorded_at,concurrency_version=NEW.episode_version_after WHERE deprivation_episode_id=episode.deprivation_episode_id;UPDATE health_deprivation_recovery_lock SET released_by_relief_receipt_id=NEW.deprivation_relief_receipt_id,released_at=NEW.recorded_at WHERE deprivation_episode_id=episode.deprivation_episode_id AND released_at IS NULL;RETURN NEW;END $$;
CREATE TRIGGER env_deprivation_relief_final BEFORE INSERT ON env_deprivation_relief_receipt FOR EACH ROW EXECUTE FUNCTION env_finalize_deprivation_relief();
CREATE FUNCTION env_reject_deprivation_history_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'Deprivation checks, relief, and recovery locks are immutable';END $$;
CREATE TRIGGER env_deprivation_check_immutable BEFORE UPDATE OR DELETE ON env_deprivation_check_receipt FOR EACH ROW EXECUTE FUNCTION env_reject_deprivation_history_mutation();CREATE TRIGGER env_deprivation_relief_immutable BEFORE UPDATE OR DELETE ON env_deprivation_relief_receipt FOR EACH ROW EXECUTE FUNCTION env_reject_deprivation_history_mutation();
CREATE FUNCTION env_guard_deprivation_state() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF pg_trigger_depth()<2 THEN RAISE EXCEPTION 'Deprivation state changes require immutable check or relief receipts' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER env_deprivation_episode_guard BEFORE UPDATE OR DELETE ON env_deprivation_episode FOR EACH ROW EXECUTE FUNCTION env_guard_deprivation_state();CREATE TRIGGER health_deprivation_lock_guard BEFORE UPDATE OR DELETE ON health_deprivation_recovery_lock FOR EACH ROW EXECUTE FUNCTION env_guard_deprivation_state();
