INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation)
SELECT artifact.source_work_id,artifact.source_artifact_id,'heading',source.heading_path,
 CASE work.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Off-World Travel: '||source.label ELSE 'Cepheus Engine v9.1, Off-World Travel: '||source.label END
FROM src_artifact artifact JOIN src_work work USING(source_work_id)
CROSS JOIN(VALUES('Off-World Travel > Ship Security > Physical Security Systems','Physical Security Systems'),('Off-World Travel > Ship Security > Cybersecurity','Cybersecurity'),('Off-World Travel > Ship Security > Security Measures','Security Measures'))source(heading_path,label)
WHERE artifact.source_uri IN('src/book2/off-world-travel.md','https://cepheus-srd.opengamingnetwork.com/cepheus-engine-srd/cepheus-engine-off-world-travel/') ON CONFLICT DO NOTHING;
WITH package AS(SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description)
SELECT content_package_id,'ship.security','Ship Security','ship','approved','Physical access controls, computer security tasks, alarms, gravity control, tranq gas, and atmosphere venting aboard vessels.' FROM package;
CREATE TABLE rule_ship_access_security(access_security_code text PRIMARY KEY,name text NOT NULL,minimum_tech_level smallint NOT NULL CHECK(minimum_tech_level>=0),means_of_access text NOT NULL,override_skill_rule_id bigint NOT NULL REFERENCES rule_skill(rule_id),external_difficulty_rule_id bigint NOT NULL REFERENCES rule_difficulty(rule_id),internal_difficulty_rule_id bigint NOT NULL REFERENCES rule_difficulty(rule_id));
INSERT INTO rule_ship_access_security SELECT value.code,value.name,value.tl,value.means,skill.rule_id,external.rule_id,internal.rule_id FROM(VALUES
 ('biometrics','Biometrics',8,'DNA test, palm print, retinal scan, or voiceprint','skill.electronics','difficulty.formidable','difficulty.very-difficult'),
 ('electronic-lock','Electronic Lock',7,'Keycard or combination','skill.electronics','difficulty.very-difficult','difficulty.difficult'),
 ('intelligent','Intelligent',9,'Granted by ship computer','skill.electronics','difficulty.formidable','difficulty.very-difficult'),
 ('mechanical-lock','Mechanical Lock',4,'Key or combination','skill.mechanics','difficulty.difficult','difficulty.average'))value(code,name,tl,means,skill_code,external_code,internal_code) JOIN rule_rule skill ON skill.rule_code=value.skill_code JOIN rule_rule external ON external.rule_code=value.external_code JOIN rule_rule internal ON internal.rule_code=value.internal_code;
CREATE TABLE rule_ship_cybersecurity_task(cybersecurity_task_code text PRIMARY KEY,name text NOT NULL,computer_skill_rule_id bigint NOT NULL REFERENCES rule_skill(rule_id),difficulty_rule_id bigint REFERENCES rule_difficulty(rule_id),security_software_defines_difficulty boolean NOT NULL,CHECK((difficulty_rule_id IS NULL)=security_software_defines_difficulty));
INSERT INTO rule_ship_cybersecurity_task SELECT value.code,value.name,skill.rule_id,difficulty.rule_id,value.software_defined FROM(VALUES('access-records','Access ship records','difficulty.average',false),('grant-authorization','Grant crew authorization','difficulty.difficult',false),('override-key-systems','Override key systems','difficulty.formidable',false),('override-security-systems','Override security systems',NULL::text,true))value(code,name,difficulty_code,software_defined) JOIN rule_rule skill ON skill.rule_code='skill.computer' LEFT JOIN rule_rule difficulty ON difficulty.rule_code=value.difficulty_code;
CREATE TABLE rule_ship_security_measure(security_measure_code text PRIMARY KEY,name text NOT NULL,maximum_gravity_g numeric(3,1),tranq_check_interval_rounds smallint,tranq_previous_check_dm smallint,vent_requires_strength_check boolean NOT NULL DEFAULT false,vent_starts_suffocation boolean NOT NULL DEFAULT false,CHECK(security_measure_code<>'artificial-gravity' OR maximum_gravity_g=3.0),CHECK(security_measure_code<>'tranq-gas' OR (tranq_check_interval_rounds=1 AND tranq_previous_check_dm=-1)),CHECK(security_measure_code<>'vent-atmosphere' OR (vent_requires_strength_check AND vent_starts_suffocation)));
INSERT INTO rule_ship_security_measure VALUES('internal-alarm','Internal Alarm',NULL,NULL,NULL,false,false),('artificial-gravity','Artificial Gravity Control',3.0,NULL,NULL,false,false),('tranq-gas','Tranq Gas',NULL,1,-1,false,false),('vent-atmosphere','Venting Atmosphere',NULL,NULL,NULL,true,true);
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation)
SELECT rule.rule_id,rule.content_package_id,locator.source_locator_id,CASE work.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,work.work_code='cepheus-engine.ogn'
FROM rule_rule rule CROSS JOIN src_locator locator JOIN src_work work USING(source_work_id) WHERE rule.rule_code='ship.security' AND locator.heading_path LIKE 'Off-World Travel > Ship Security > %' AND work.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');
