INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation)
SELECT DISTINCT ON(work.work_code,source.heading_path) artifact.source_work_id,artifact.source_artifact_id,'heading',source.heading_path,CASE work.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Off-World Travel: '||source.label ELSE 'Cepheus Engine v9.1, Off-World Travel: '||source.label END
FROM src_artifact artifact JOIN src_work work USING(source_work_id) CROSS JOIN(VALUES('Off-World Travel > Characters and the Law','Characters and the Law'),('Off-World Travel > Characters and the Law > Arrests and Sentencing','Arrests and Sentencing'))source(heading_path,label)
WHERE artifact.source_uri IN('src/book2/off-world-travel.md','https://cepheus-srd.opengamingnetwork.com/cepheus-engine-srd/cepheus-engine-off-world-travel/') ORDER BY work.work_code,source.heading_path,artifact.source_artifact_id ON CONFLICT DO NOTHING;
WITH package AS(SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description) SELECT content_package_id,'world.law-enforcement','Law Enforcement and Sentencing','world','approved','Law-level encounter checks, investigation escalation, crime modifiers, advocacy, and sentencing consequences.' FROM package;
CREATE TABLE rule_law_encounter_situation(situation_code text PRIMARY KEY,name text NOT NULL,encounter_dm smallint NOT NULL,response_kind text NOT NULL CHECK(response_kind IN('check','investigate','combat')),frequency_limit text CHECK(frequency_limit IN('first-approach','once-per-day')));
INSERT INTO rule_law_encounter_situation VALUES('first-approach','First approach to a planet',0,'check','first-approach'),('offworlders-wandering','Offworlders wandering city streets',0,'check','once-per-day'),('offworlders-suspicious','Offworlders acting suspiciously',-1,'check',NULL),('bar-fight','Bar fight',-1,'combat',NULL),('shots-fired','Shots fired',-2,'combat',NULL),('breaking-entering','Breaking and entering',-2,'investigate',NULL),('armored-firefight','Firefight with armor and military weapons',-4,'combat',NULL),('murder-carnage','Murder and carnage',-4,'investigate',NULL);
CREATE TABLE rule_sentencing_crime(crime_code text PRIMARY KEY,name text NOT NULL,law_level_offset smallint,smuggling_banned_goods_difference boolean NOT NULL DEFAULT false,CHECK((law_level_offset IS NULL)=smuggling_banned_goods_difference));
INSERT INTO rule_sentencing_crime VALUES('assault','Assault',-5,false),('destruction-property','Destruction of Property',-3,false),('false-identity','False Identity',-2,false),('manslaughter','Manslaughter',-1,false),('murder','Murder',0,false),('smuggling','Smuggling Banned Goods',NULL,true);
CREATE TABLE rule_sentencing_band(sentencing_band_code text PRIMARY KEY,result_minimum smallint,result_maximum smallint,CHECK(result_maximum IS NULL OR result_maximum>=result_minimum));
INSERT INTO rule_sentencing_band VALUES('dismissed',-32768,0),('minor-fine',1,2),('major-fine',3,4),('exile-or-fine',5,6),('months-exile-or-fine',7,8),('years-or-exile',9,10),('long-years-or-exile',11,12),('life',13,14),('death',15,NULL);
CREATE TABLE rule_sentencing_consequence(sentencing_band_code text NOT NULL REFERENCES rule_sentencing_band(sentencing_band_code),consequence_code text NOT NULL,consequence_kind text NOT NULL CHECK(consequence_kind IN('dismissed','trivial','fine','exile','imprisonment','life-imprisonment','death')),dice_count smallint CHECK(dice_count>0),die_sides smallint CHECK(die_sides>1),multiplier integer CHECK(multiplier>0),measurement_unit text CHECK(measurement_unit IN('credits','months','years')),PRIMARY KEY(sentencing_band_code,consequence_code),CHECK((dice_count IS NULL)=(die_sides IS NULL)),CHECK((multiplier IS NULL)=(measurement_unit IS NULL)));
INSERT INTO rule_sentencing_consequence VALUES
('dismissed','dismissed','dismissed',NULL,NULL,NULL,NULL),('dismissed','trivial','trivial',NULL,NULL,NULL,NULL),('minor-fine','fine','fine',1,6,1000,'credits'),('major-fine','fine','fine',2,6,5000,'credits'),('exile-or-fine','exile','exile',NULL,NULL,NULL,NULL),('exile-or-fine','fine','fine',2,6,10000,'credits'),('months-exile-or-fine','imprisonment','imprisonment',1,6,1,'months'),('months-exile-or-fine','exile','exile',NULL,NULL,NULL,NULL),('months-exile-or-fine','fine','fine',2,6,20000,'credits'),('years-or-exile','imprisonment','imprisonment',1,6,1,'years'),('years-or-exile','exile','exile',NULL,NULL,NULL,NULL),('long-years-or-exile','imprisonment','imprisonment',2,6,1,'years'),('long-years-or-exile','exile','exile',NULL,NULL,NULL,NULL),('life','life','life-imprisonment',NULL,NULL,NULL,NULL),('death','death','death',NULL,NULL,NULL,NULL);
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT rule.rule_id,rule.content_package_id,locator.source_locator_id,CASE work.work_code WHEN 'cepheus-engine.ogn' THEN 'direct' ELSE 'corroborating' END,work.work_code='cepheus-engine.ogn' FROM rule_rule rule CROSS JOIN src_locator locator JOIN src_work work USING(source_work_id) WHERE rule.rule_code='world.law-enforcement' AND locator.heading_path LIKE 'Off-World Travel > Characters and the Law%' AND work.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');
