INSERT INTO src_locator(source_work_id,source_artifact_id,locator_type,heading_path,display_citation)
SELECT a.source_work_id,a.source_artifact_id,'heading','Refereeing the Game > Improvisation > Improvisational Preparation',CASE w.work_code WHEN 'cepheus-engine.ogn' THEN 'Cepheus Engine SRD, Improvisational Preparation' ELSE 'Cepheus Engine v9.1, Improvisational Preparation' END
FROM src_artifact a JOIN src_work w USING(source_work_id) WHERE (w.work_code='cepheus-engine.github-v9.1' AND a.source_uri='src/book3/refereeing-the-game.md') OR (w.work_code='cepheus-engine.ogn' AND a.source_uri='https://cepheus-srd.opengamingnetwork.com/cepheus-engine-srd/cepheus-engine-refereeing-the-game/') ON CONFLICT DO NOTHING;
WITH p AS(SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine') INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status,description) SELECT content_package_id,'referee.structured-scene-preparation','Structured Scene Preparation','encounter','approved','Agreed application convention: reusable scene blueprints preserve authoritative facts while narration remains generated and flexible.' FROM p;
INSERT INTO src_record_provenance(rule_id,content_package_id,source_locator_id,provenance_class,is_primary_citation) SELECT r.rule_id,r.content_package_id,l.source_locator_id,'agreed_addition',w.work_code='cepheus-engine.ogn' FROM rule_rule r CROSS JOIN src_locator l JOIN src_work w USING(source_work_id) WHERE r.rule_code='referee.structured-scene-preparation' AND l.heading_path='Refereeing the Game > Improvisation > Improvisational Preparation' AND w.work_code IN('cepheus-engine.ogn','cepheus-engine.github-v9.1');

CREATE TABLE rule_scene_template(scene_template_code text PRIMARY KEY,name text NOT NULL UNIQUE,display_order smallint NOT NULL UNIQUE CHECK(display_order>0));
INSERT INTO rule_scene_template VALUES('port-arrival','Port Arrival',1),('docking-customs','Docking and Customs',2),('jump-transition','Jump Transition',3),('wilderness-travel','Wilderness Travel',4),('weather-change','Weather Change',5),('law-stop','Law Stop',6),('market-visit','Market Visit',7),('distress-call','Distress Call',8);
CREATE TABLE rule_scene_template_slot(scene_template_code text NOT NULL REFERENCES rule_scene_template,slot_code text NOT NULL,slot_name text NOT NULL,data_kind text NOT NULL CHECK(data_kind IN('actor','condition','location','number','procedure','resource','status','time','world','other')),slot_order smallint NOT NULL CHECK(slot_order>0),required boolean NOT NULL,PRIMARY KEY(scene_template_code,slot_code),UNIQUE(scene_template_code,slot_order));
INSERT INTO rule_scene_template_slot VALUES
 ('port-arrival','port','Port','location',1,true),('port-arrival','vessel','Vessel','resource',2,true),('port-arrival','arrival-status','Arrival Status','status',3,true),('port-arrival','local-condition','Local Condition','condition',4,false),
 ('docking-customs','facility','Docking Facility','location',1,true),('docking-customs','clearance','Clearance','status',2,true),('docking-customs','berth','Berth','location',3,false),('docking-customs','inspection','Inspection','procedure',4,false),
 ('jump-transition','origin','Origin','world',1,true),('jump-transition','destination','Destination','world',2,true),('jump-transition','duration','Duration','time',3,true),('jump-transition','transition-status','Transition Status','status',4,true),
 ('wilderness-travel','terrain','Terrain','condition',1,true),('wilderness-travel','route','Route','location',2,true),('wilderness-travel','pace','Pace','procedure',3,true),('wilderness-travel','hazard','Hazard','condition',4,false),
 ('weather-change','conditions','Conditions','condition',1,true),('weather-change','visibility','Visibility','condition',2,true),('weather-change','temperature','Temperature','condition',3,false),('weather-change','mechanical-effect','Mechanical Effect','procedure',4,false),
 ('law-stop','authority','Authority','actor',1,true),('law-stop','law-level','Law Level','number',2,true),('law-stop','reason','Reason','procedure',3,true),('law-stop','disposition','Disposition','status',4,false),
 ('market-visit','market','Market','location',1,true),('market-visit','availability','Availability','resource',2,true),('market-visit','price-context','Price Context','condition',3,true),('market-visit','constraint','Notable Constraint','condition',4,false),
 ('distress-call','signal-source','Signal Source','actor',1,true),('distress-call','signal-location','Signal Location','location',2,true),('distress-call','signal-content','Signal Content','other',3,true),('distress-call','credibility','Credibility','status',4,true);

DO $$ DECLARE d text; BEGIN SELECT pg_get_constraintdef(oid) INTO STRICT d FROM pg_constraint WHERE conrelid='cmd_command'::regclass AND conname='cmd_command_command_type_check'; ALTER TABLE cmd_command DROP CONSTRAINT cmd_command_command_type_check; EXECUTE format('ALTER TABLE cmd_command ADD CONSTRAINT cmd_command_command_type_check %s',replace(d,'CHECK (','CHECK (command_type=''create_scene_snapshot'' OR ')); END $$;
CREATE TABLE camp_scene_snapshot(scene_snapshot_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,public_id uuid NOT NULL DEFAULT gen_random_uuid() UNIQUE,campaign_id bigint NOT NULL REFERENCES camp_campaign,scene_template_code text NOT NULL REFERENCES rule_scene_template,location_id bigint,encounter_id bigint,journey_id bigint,scene_reference text NOT NULL CHECK(btrim(scene_reference)<>''),created_by_reference text NOT NULL CHECK(btrim(created_by_reference)<>''),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(scene_snapshot_id,campaign_id),FOREIGN KEY(location_id,campaign_id) REFERENCES loc_location(location_id,campaign_id),FOREIGN KEY(encounter_id,campaign_id) REFERENCES enc_encounter(encounter_id,campaign_id),FOREIGN KEY(journey_id,campaign_id) REFERENCES journey_journey(journey_id,campaign_id),CHECK(num_nonnulls(location_id,encounter_id,journey_id)<=1));
CREATE TABLE camp_scene_fact(scene_snapshot_id bigint NOT NULL,campaign_id bigint NOT NULL,slot_code text NOT NULL,fact_value text NOT NULL CHECK(btrim(fact_value)<>''),source_reference text CHECK(source_reference IS NULL OR btrim(source_reference)<>''),PRIMARY KEY(scene_snapshot_id,slot_code),FOREIGN KEY(scene_snapshot_id,campaign_id) REFERENCES camp_scene_snapshot(scene_snapshot_id,campaign_id));
CREATE TABLE cmd_scene_snapshot_receipt(command_id bigint PRIMARY KEY REFERENCES cmd_command,scene_snapshot_id bigint NOT NULL UNIQUE,campaign_id bigint NOT NULL REFERENCES camp_campaign,scene_template_code text NOT NULL REFERENCES rule_scene_template,fact_count smallint NOT NULL CHECK(fact_count>0),FOREIGN KEY(scene_snapshot_id,campaign_id) REFERENCES camp_scene_snapshot(scene_snapshot_id,campaign_id));
CREATE FUNCTION enc_validate_scene_snapshot_receipt() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE actual_template text;actual_count integer;missing integer;unknown integer;
BEGIN SELECT scene_template_code INTO STRICT actual_template FROM camp_scene_snapshot WHERE scene_snapshot_id=NEW.scene_snapshot_id;SELECT count(*) INTO actual_count FROM camp_scene_fact WHERE scene_snapshot_id=NEW.scene_snapshot_id;SELECT count(*) INTO missing FROM rule_scene_template_slot s WHERE s.scene_template_code=actual_template AND s.required AND NOT EXISTS(SELECT 1 FROM camp_scene_fact f WHERE f.scene_snapshot_id=NEW.scene_snapshot_id AND f.slot_code=s.slot_code);SELECT count(*) INTO unknown FROM camp_scene_fact f WHERE f.scene_snapshot_id=NEW.scene_snapshot_id AND NOT EXISTS(SELECT 1 FROM rule_scene_template_slot s WHERE s.scene_template_code=actual_template AND s.slot_code=f.slot_code);
 IF actual_template<>NEW.scene_template_code OR actual_count<>NEW.fact_count OR missing>0 OR unknown>0 THEN RAISE EXCEPTION 'Scene snapshot does not satisfy its structured template' USING ERRCODE='23514';END IF;RETURN NEW;END $$;
CREATE TRIGGER cmd_scene_snapshot_receipt_valid BEFORE INSERT ON cmd_scene_snapshot_receipt FOR EACH ROW EXECUTE FUNCTION enc_validate_scene_snapshot_receipt();
CREATE FUNCTION enc_reject_sealed_scene_mutation() RETURNS trigger LANGUAGE plpgsql AS $$DECLARE snapshot bigint;BEGIN snapshot:=OLD.scene_snapshot_id;IF EXISTS(SELECT 1 FROM cmd_scene_snapshot_receipt WHERE scene_snapshot_id=snapshot) THEN RAISE EXCEPTION 'Sealed scene snapshot is immutable' USING ERRCODE='55000';END IF;IF TG_OP='DELETE' THEN RETURN OLD;END IF;RETURN NEW;END $$;
CREATE TRIGGER camp_scene_snapshot_immutable BEFORE UPDATE OR DELETE ON camp_scene_snapshot FOR EACH ROW EXECUTE FUNCTION enc_reject_sealed_scene_mutation();
CREATE TRIGGER camp_scene_fact_immutable BEFORE UPDATE OR DELETE ON camp_scene_fact FOR EACH ROW EXECUTE FUNCTION enc_reject_sealed_scene_mutation();
CREATE TRIGGER cmd_scene_snapshot_receipt_immutable BEFORE UPDATE OR DELETE ON cmd_scene_snapshot_receipt FOR EACH ROW EXECUTE FUNCTION enc_reject_social_content_selection_mutation();
