INSERT INTO cmd_command_type VALUES('review_campaign_source_page','Review campaign source page'),('publish_campaign_source_intro','Publish player-safe source introduction'),('reveal_campaign_source_excerpt','Reveal campaign source excerpt');
INSERT INTO cmd_domain_event_type VALUES('campaign_source_page_reviewed','Campaign source page reviewed'),('campaign_source_intro_published','Campaign source introduction published'),('campaign_source_excerpt_revealed','Campaign source excerpt revealed');
CREATE TABLE camp_source_page_review(
 source_page_review_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,source_document_id bigint NOT NULL,campaign_id bigint NOT NULL,page_number integer NOT NULL,
 review_order integer NOT NULL CHECK(review_order>0),reviewer_kind text NOT NULL CHECK(reviewer_kind IN('ai_referee','system_operator')),
 text_verified boolean NOT NULL,visual_verified boolean NOT NULL,generic_issue_code text CHECK(generic_issue_code IN('unreadable','partial_text','visual_check_required','damaged_file','unsupported_content')),
 private_review_note text NOT NULL DEFAULT '',reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp(),source_command_id bigint NOT NULL REFERENCES cmd_command(command_id),
 UNIQUE(source_document_id,page_number,review_order),FOREIGN KEY(source_document_id,page_number) REFERENCES camp_source_page(source_document_id,page_number),FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id)
);
CREATE VIEW camp_source_latest_page_review AS SELECT DISTINCT ON(source_document_id,page_number) * FROM camp_source_page_review ORDER BY source_document_id,page_number,review_order DESC;
CREATE TABLE camp_source_player_intro(source_document_id bigint PRIMARY KEY,campaign_id bigint NOT NULL,introduction_text text NOT NULL CHECK(btrim(introduction_text)<>''),published_at timestamptz NOT NULL DEFAULT clock_timestamp(),source_command_id bigint NOT NULL REFERENCES cmd_command(command_id),FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id));
CREATE TABLE camp_source_revealed_excerpt(revealed_excerpt_id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,source_document_id bigint NOT NULL,campaign_id bigint NOT NULL,page_number integer NOT NULL,excerpt_text text NOT NULL CHECK(btrim(excerpt_text)<>''),reveal_reason text NOT NULL CHECK(btrim(reveal_reason)<>''),revealed_day bigint NOT NULL,revealed_at timestamptz NOT NULL DEFAULT clock_timestamp(),source_command_id bigint NOT NULL REFERENCES cmd_command(command_id),FOREIGN KEY(source_document_id,page_number) REFERENCES camp_source_page(source_document_id,page_number),FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id));
CREATE VIEW camp_player_visible_source AS SELECT document.source_document_id,document.campaign_id,document.public_id,document.title,document.source_kind,document.ingestion_status,intro.introduction_text,NULL::integer AS page_number,NULL::text AS revealed_excerpt,NULL::bigint AS revealed_day FROM camp_source_document document LEFT JOIN camp_source_player_intro intro USING(source_document_id,campaign_id) UNION ALL SELECT document.source_document_id,document.campaign_id,document.public_id,document.title,document.source_kind,document.ingestion_status,NULL,excerpt.page_number,excerpt.excerpt_text,excerpt.revealed_day FROM camp_source_document document JOIN camp_source_revealed_excerpt excerpt USING(source_document_id,campaign_id);
CREATE FUNCTION camp_apply_source_page_review() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE complete boolean; any_failed boolean;
BEGIN
 UPDATE camp_source_page SET review_status=CASE WHEN NEW.text_verified AND (NOT visual_review_required OR NEW.visual_verified) THEN 'verified' ELSE 'rejected' END WHERE source_document_id=NEW.source_document_id AND page_number=NEW.page_number;
 SELECT bool_and(page.review_status='verified'),bool_or(page.review_status='rejected') INTO complete,any_failed FROM camp_source_page page WHERE page.source_document_id=NEW.source_document_id;
 UPDATE camp_source_document SET ingestion_status=CASE WHEN complete THEN 'ready' WHEN any_failed THEN 'failed' ELSE 'needs_review' END WHERE source_document_id=NEW.source_document_id;
 RETURN NEW;
END $$;
CREATE TRIGGER camp_source_review_apply AFTER INSERT ON camp_source_page_review FOR EACH ROW EXECUTE FUNCTION camp_apply_source_page_review();
CREATE TABLE cmd_campaign_source_page_review_receipt(command_id bigint PRIMARY KEY REFERENCES cmd_command(command_id),campaign_id bigint NOT NULL REFERENCES camp_campaign(campaign_id),source_page_review_id bigint NOT NULL UNIQUE REFERENCES camp_source_page_review(source_page_review_id),source_document_id bigint NOT NULL,page_number integer NOT NULL,review_status text NOT NULL CHECK(review_status IN('verified','rejected')),FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id));
CREATE TABLE cmd_campaign_source_intro_receipt(command_id bigint PRIMARY KEY REFERENCES cmd_command(command_id),campaign_id bigint NOT NULL REFERENCES camp_campaign(campaign_id),source_document_id bigint NOT NULL UNIQUE,FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id));
CREATE TABLE cmd_campaign_source_reveal_receipt(command_id bigint PRIMARY KEY REFERENCES cmd_command(command_id),campaign_id bigint NOT NULL REFERENCES camp_campaign(campaign_id),revealed_excerpt_id bigint NOT NULL UNIQUE REFERENCES camp_source_revealed_excerpt(revealed_excerpt_id),source_document_id bigint NOT NULL,page_number integer NOT NULL,FOREIGN KEY(source_document_id,campaign_id) REFERENCES camp_source_document(source_document_id,campaign_id));
UPDATE camp_source_page SET review_status='pending';
UPDATE camp_source_document SET ingestion_status='needs_review';
