"""Human-reviewed, full-page-accounted indexing for uploaded adventures."""
from __future__ import annotations
from dataclasses import dataclass
import psycopg

@dataclass(frozen=True)
class IndexResult:
 command_public_id:str;session_public_id:str;proposal_public_id:str|None;result_code:str;replayed:bool

def _old(c,authority,key,kind):
 row=c.execute("SELECT command_id,public_id,command_type FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(authority,key)).fetchone()
 if row and row[2]!=kind:raise ValueError('Idempotency key belongs to another command')
 return row
def _result(c,row,replayed):
 value=c.execute("SELECT session.public_id,proposal.public_id,receipt.result_code FROM cmd_adventure_indexing_receipt receipt JOIN camp_adventure_index_session session USING(adventure_index_session_id) LEFT JOIN camp_adventure_location_proposal proposal USING(adventure_location_proposal_id) WHERE receipt.command_id=%s",(row[0],)).fetchone();return IndexResult(str(row[1]),str(value[0]),str(value[1]) if value[1] else None,value[2],replayed)
def _finish(c,command,campaign,session,page,proposal,result,event):
 c.execute("INSERT INTO cmd_adventure_indexing_receipt(command_id,campaign_id,adventure_index_session_id,source_page_number,adventure_location_proposal_id,result_code) VALUES(%s,%s,%s,%s,%s,%s)",(command[0],campaign,session,page,proposal,result));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,%s)",(command[0],event));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(command[0],))

def begin_adventure_indexing_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,module_public_id:str)->IndexResult:
 with c.transaction():
  old=_old(c,initiator_reference,idempotency_key,'begin_adventure_indexing')
  if old:return _result(c,old,True)
  module=c.execute("SELECT module.adventure_module_id,module.campaign_id,module.source_document_id FROM camp_adventure_module module JOIN camp_campaign campaign USING(campaign_id) JOIN camp_source_document document ON document.source_document_id=module.source_document_id WHERE module.public_id=%s AND campaign.owner_reference=%s AND document.ingestion_status='ready'",(module_public_id,initiator_reference)).fetchone()
  if not module:raise ValueError('Indexing requires a fully reviewed adventure source')
  command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('begin_adventure_indexing',%s,%s) RETURNING command_id,public_id,command_type",(initiator_reference,idempotency_key)).fetchone();session,public=c.execute("INSERT INTO camp_adventure_index_session(adventure_module_id,campaign_id,source_document_id,source_command_id) VALUES(%s,%s,%s,%s) RETURNING adventure_index_session_id,public_id",(module[0],module[1],module[2],command[0])).fetchone();c.execute("INSERT INTO camp_adventure_index_page(adventure_index_session_id,source_document_id,page_number) SELECT %s,source_document_id,page_number FROM camp_source_page WHERE source_document_id=%s AND review_status='verified' ORDER BY page_number",(session,module[2]));_finish(c,command,module[1],session,None,None,'reading','adventure_indexing_begun');return IndexResult(str(command[1]),str(public),None,'reading',False)

def read_adventure_source_page_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,session_public_id:str,page_number:int)->dict:
 with c.transaction():
  old=_old(c,initiator_reference,idempotency_key,'read_adventure_source_page')
  if old:
   receipt=_result(c,old,True);text=c.execute("SELECT page.text_content FROM camp_adventure_index_session session JOIN camp_adventure_index_page indexed USING(adventure_index_session_id) JOIN camp_source_page page ON page.source_document_id=indexed.source_document_id AND page.page_number=indexed.page_number WHERE session.public_id=%s AND indexed.page_number=%s",(receipt.session_public_id,page_number)).fetchone()[0];return {'receipt':receipt,'page_number':page_number,'text':text}
  row=c.execute("SELECT session.adventure_index_session_id,session.campaign_id,page.source_document_id,page.text_content FROM camp_adventure_index_session session JOIN camp_campaign campaign USING(campaign_id) JOIN camp_adventure_index_page indexed USING(adventure_index_session_id) JOIN camp_source_page page ON page.source_document_id=indexed.source_document_id AND page.page_number=indexed.page_number WHERE session.public_id=%s AND indexed.page_number=%s AND campaign.owner_reference=%s FOR UPDATE OF session,indexed",(session_public_id,page_number,initiator_reference)).fetchone()
  if not row:raise PermissionError('Index page is outside this authority')
  command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('read_adventure_source_page',%s,%s) RETURNING command_id,public_id,command_type",(initiator_reference,idempotency_key)).fetchone();c.execute("UPDATE camp_adventure_index_page SET page_status='read',read_command_id=%s,read_at=clock_timestamp() WHERE adventure_index_session_id=%s AND page_number=%s",(command[0],row[0],page_number));pending=c.execute("SELECT count(*) FROM camp_adventure_index_page WHERE adventure_index_session_id=%s AND page_status='pending'",(row[0],)).fetchone()[0];status='ready_for_proposals' if pending==0 else 'reading';c.execute("UPDATE camp_adventure_index_session SET indexing_status=%s WHERE adventure_index_session_id=%s",(status,row[0]));_finish(c,command,row[1],row[0],page_number,None,status,'adventure_source_page_read');return {'receipt':IndexResult(str(command[1]),session_public_id,None,status,False),'page_number':page_number,'text':row[3],'pages_remaining':pending}

def propose_adventure_location_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,session_public_id:str,source_page_number:int,source_excerpt:str,location_key:str,name:str,keyed_description:str,occupants_initial:str|None=None,treasure_initial:str|None=None)->IndexResult:
 with c.transaction():
  old=_old(c,initiator_reference,idempotency_key,'propose_adventure_location')
  if old:return _result(c,old,True)
  session=c.execute("SELECT session.adventure_index_session_id,session.campaign_id,session.source_document_id,page.text_content FROM camp_adventure_index_session session JOIN camp_campaign campaign USING(campaign_id) JOIN camp_source_page page ON page.source_document_id=session.source_document_id AND page.page_number=%s WHERE session.public_id=%s AND campaign.owner_reference=%s AND NOT EXISTS(SELECT 1 FROM camp_adventure_index_page unread WHERE unread.adventure_index_session_id=session.adventure_index_session_id AND unread.page_status<>'read')",(source_page_number,session_public_id,initiator_reference)).fetchone()
  if not session:raise ValueError('Every verified page must be read before locations may be proposed')
  excerpt=source_excerpt.strip()
  if not excerpt or excerpt not in session[3]:raise ValueError('Proposal citation must be an exact excerpt from its verified page')
  if not all((location_key.strip(),name.strip(),keyed_description.strip())):raise ValueError('Key, name, and description are required')
  command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('propose_adventure_location',%s,%s) RETURNING command_id,public_id,command_type",(initiator_reference,idempotency_key)).fetchone();proposal,public=c.execute("INSERT INTO camp_adventure_location_proposal(adventure_index_session_id,campaign_id,source_document_id,source_page_number,location_key,name,keyed_description,source_excerpt,occupants_initial,treasure_initial,proposed_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING adventure_location_proposal_id,public_id",(session[0],session[1],session[2],source_page_number,location_key.strip(),name.strip(),keyed_description.strip(),excerpt,occupants_initial.strip() if occupants_initial else None,treasure_initial.strip() if treasure_initial else None,command[0])).fetchone();c.execute("UPDATE camp_adventure_index_session SET indexing_status='under_review' WHERE adventure_index_session_id=%s",(session[0],));_finish(c,command,session[1],session[0],source_page_number,proposal,'pending_review','adventure_location_proposed');return IndexResult(str(command[1]),session_public_id,str(public),'pending_review',False)

def review_adventure_location_proposal_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,proposal_public_id:str,decision:str,review_note:str='')->IndexResult:
 if decision not in ('approve','reject'):raise ValueError('Decision must be approve or reject')
 with c.transaction():
  old=_old(c,initiator_reference,idempotency_key,'review_adventure_location_proposal')
  if old:return _result(c,old,True)
  row=c.execute("SELECT proposal.adventure_location_proposal_id,proposal.adventure_index_session_id,proposal.campaign_id,session.adventure_module_id,session.public_id,proposal.location_key,proposal.name,proposal.keyed_description,proposal.source_page_number,proposal.occupants_initial,proposal.treasure_initial FROM camp_adventure_location_proposal proposal JOIN camp_adventure_index_session session USING(adventure_index_session_id,campaign_id) JOIN camp_campaign campaign USING(campaign_id) WHERE proposal.public_id=%s AND proposal.proposal_status='pending' AND campaign.owner_reference=%s FOR UPDATE OF proposal,session",(proposal_public_id,initiator_reference)).fetchone()
  if not row:raise PermissionError('Pending proposal is outside this authority')
  command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('review_adventure_location_proposal',%s,%s) RETURNING command_id,public_id,command_type",(initiator_reference,idempotency_key)).fetchone();location=None
  if decision=='approve':location=c.execute("INSERT INTO camp_adventure_location(adventure_module_id,campaign_id,location_key,name,keyed_description,source_page_number,occupants_initial,treasure_initial,source_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING adventure_location_id",(row[3],row[2],row[5],row[6],row[7],row[8],row[9],row[10],command[0])).fetchone()[0]
  c.execute("UPDATE camp_adventure_location_proposal SET proposal_status=%s,review_note=NULLIF(btrim(%s),''),reviewed_command_id=%s,approved_location_id=%s,reviewed_at=clock_timestamp() WHERE adventure_location_proposal_id=%s",('approved' if decision=='approve' else 'rejected',review_note,command[0],location,row[0]));pending=c.execute("SELECT count(*) FROM camp_adventure_location_proposal WHERE adventure_index_session_id=%s AND proposal_status='pending'",(row[1],)).fetchone()[0];c.execute("UPDATE camp_adventure_index_session SET indexing_status=%s WHERE adventure_index_session_id=%s",('complete' if pending==0 else 'under_review',row[1]));_finish(c,command,row[2],row[1],row[8],row[0],decision+'d','adventure_location_proposal_reviewed');return IndexResult(str(command[1]),str(row[4]),proposal_public_id,decision+'d',False)

def adventure_index_snapshot(c:psycopg.Connection,*,initiator_reference:str,module_public_id:str)->dict|None:
 session=c.execute("SELECT session.adventure_index_session_id,session.public_id,session.indexing_status,document.title,count(*) AS pages,count(*) FILTER(WHERE page.page_status='read') AS pages_read FROM camp_adventure_index_session session JOIN camp_adventure_module module ON module.adventure_module_id=session.adventure_module_id AND module.campaign_id=session.campaign_id JOIN camp_campaign campaign ON campaign.campaign_id=session.campaign_id JOIN camp_source_document document ON document.source_document_id=session.source_document_id AND document.campaign_id=session.campaign_id JOIN camp_adventure_index_page page ON page.adventure_index_session_id=session.adventure_index_session_id WHERE module.public_id=%s AND campaign.owner_reference=%s GROUP BY session.adventure_index_session_id,document.title",(module_public_id,initiator_reference)).fetchone()
 if not session:return None
 proposals=c.execute("SELECT public_id,location_key,name,keyed_description,source_page_number,source_excerpt,occupants_initial,treasure_initial,proposal_status,review_note FROM camp_adventure_location_proposal WHERE adventure_index_session_id=%s ORDER BY source_page_number,location_key",(session[0],)).fetchall()
 return {'public_id':str(session[1]),'status':session[2],'source_title':session[3],'page_count':session[4],'pages_read':session[5],'proposals':[{'public_id':str(r[0]),'key':r[1],'name':r[2],'description':r[3],'source_page':r[4],'source_excerpt':r[5],'occupants':r[6],'treasure':r[7],'status':r[8],'review_note':r[9]} for r in proposals]}
