"""Task-backed Demolitions, Electronics, and Mechanics device operations."""
from dataclasses import dataclass
import psycopg
from engine.tasks import resolve_actor_task_command
@dataclass(frozen=True)
class DeviceOperationResult:
 command_public_id:str;actor_public_id:str;operation_code:str;device_reference:str;skill_rule_code:str;check_total:int;effect:int;succeeded:bool;replayed:bool
def resolve_device_operation_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,actor_public_id:str,operation_code:str,device_reference:str,characteristic_rule_code:str,difficulty_rule_code:str,location_public_id:str|None=None,item_instance_public_id:str|None=None,random_source=None)->DeviceOperationResult:
 if not device_reference.strip():raise ValueError('Device reference is required')
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('resolve_device_operation','completed'):raise RuntimeError('Idempotency key belongs to another command')
   r=c.execute("SELECT a.public_id,x.operation_code,x.device_reference,s.rule_code,x.check_total,x.effect,x.succeeded FROM cmd_device_operation_receipt x JOIN actor_actor a ON a.actor_id=x.actor_id JOIN rule_device_operation o ON o.rule_id=x.operation_rule_id AND o.operation_code=x.operation_code JOIN rule_rule s ON s.rule_id=o.skill_rule_id WHERE x.command_id=%s",(old[0],)).fetchone();return DeviceOperationResult(str(old[1]),str(r[0]),r[1],r[2],r[3],r[4],r[5],r[6],True)
  state=c.execute("SELECT a.actor_id,a.campaign_id,m.rule_id,o.skill_rule_id,s.rule_code,l.location_id,i.item_instance_id FROM actor_actor a JOIN rule_device_operation_mechanic m ON true JOIN rule_device_operation o ON o.rule_id=m.rule_id AND o.operation_code=%s JOIN rule_rule s ON s.rule_id=o.skill_rule_id LEFT JOIN loc_location l ON l.public_id=%s AND l.campaign_id=a.campaign_id LEFT JOIN inv_item_instance i ON i.public_id=%s AND i.campaign_id=a.campaign_id WHERE a.public_id=%s AND a.controller_reference=%s FOR UPDATE OF a",(operation_code,location_public_id,item_instance_public_id,actor_public_id,initiator_reference)).fetchone()
  if not state or (location_public_id is not None and state[5] is None) or (item_instance_public_id is not None and state[6] is None):raise ValueError('Device operation context is not legal for this campaign')
  task=resolve_actor_task_command(c,initiator_reference=initiator_reference,idempotency_key=f'device:{idempotency_key}',actor_public_id=actor_public_id,characteristic_rule_code=characteristic_rule_code,skill_rule_code=state[4],difficulty_rule_code=difficulty_rule_code,random_source=random_source);task_id=c.execute("SELECT command_id FROM cmd_command WHERE public_id=%s",(task.command_public_id,)).fetchone()[0];cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('resolve_device_operation',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();c.execute("INSERT INTO cmd_device_operation_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(cid,state[1],state[0],state[2],operation_code,device_reference.strip(),state[5],state[6],task_id,task.total,task.effect,task.succeeded));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return DeviceOperationResult(str(pub),actor_public_id,operation_code,device_reference.strip(),state[4],task.total,task.effect,task.succeeded,False)
