"""Postal contract acceptance, secure capacity, and delivery settlement."""
from dataclasses import dataclass
import secrets
import psycopg
@dataclass(frozen=True)
class PostalAcceptanceResult:
 command_public_id:str;contract_public_id:str;journey_public_id:str;ship_public_id:str;actual_mail_tons:int;reserved_mail_tons:int;promised_payment:int;replayed:bool
@dataclass(frozen=True)
class PostalDeliveryResult:
 command_public_id:str;contract_public_id:str;ship_public_id:str;actual_mail_tons:int;paid_credits:int;balance_after:int;replayed:bool
def _accept(c,cid,pub,replayed):
 r=c.execute("SELECT contract.public_id,journey.public_id,ship.public_id,receipt.actual_mail_tons,receipt.reserved_mail_tons,receipt.promised_payment_credits FROM cmd_postal_contract_acceptance_receipt receipt JOIN journey_postal_contract contract USING(postal_contract_id) JOIN journey_journey journey USING(journey_id) JOIN ship_ship ship USING(ship_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return PostalAcceptanceResult(str(pub),str(r[0]),str(r[1]),str(r[2]),r[3],r[4],r[5],replayed)
def _deliver(c,cid,pub,replayed):
 r=c.execute("SELECT contract.public_id,ship.public_id,contract.actual_mail_tons,delivery.paid_credits,receipt.balance_after_minor FROM cmd_postal_contract_delivery_receipt receipt JOIN journey_postal_contract contract USING(postal_contract_id) JOIN ship_ship ship USING(ship_id) JOIN journey_postal_delivery_receipt delivery USING(postal_contract_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return PostalDeliveryResult(str(pub),str(r[0]),str(r[1]),r[2],r[3],r[4],replayed)
def accept_postal_contract_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,journey_public_id:str,random_source=None)->PostalAcceptanceResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('accept_postal_contract','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _accept(c,old[0],old[1],True)
  s=c.execute("""SELECT journey.campaign_id,journey.journey_id,leg.journey_leg_id,journey.ship_id,ship.public_id,class.cargo_capacity_tons,assignment.crew_assignment_id,setup.cargo_container_id
 FROM journey_journey journey JOIN camp_campaign campaign USING(campaign_id) JOIN journey_leg leg ON leg.journey_id=journey.journey_id AND leg.leg_order=1 JOIN ship_ship ship USING(ship_id) JOIN ship_class class USING(ship_class_rule_id)
 JOIN ship_crew_assignment assignment ON assignment.ship_id=ship.ship_id AND assignment.duty_status='active' JOIN ship_crew_position position USING(ship_crew_position_id,ship_id,campaign_id) JOIN ship_crew_position_definition definition ON definition.crew_position_rule_id=position.crew_position_rule_id AND definition.position_code='gunner'
 JOIN cmd_trading_preparation_receipt setup ON setup.campaign_id=journey.campaign_id AND setup.ship_id=ship.ship_id
 WHERE journey.public_id=%s AND campaign.owner_reference=%s AND journey.journey_status IN('planning','ready') AND EXISTS(SELECT 1 FROM ship_class_weapon weapon WHERE weapon.ship_class_rule_id=ship.ship_class_rule_id AND weapon.quantity>0) AND NOT EXISTS(SELECT 1 FROM journey_postal_contract postal WHERE postal.journey_id=journey.journey_id) ORDER BY assignment.crew_assignment_id LIMIT 1 FOR UPDATE OF journey,ship,assignment""",(journey_public_id,initiator_reference)).fetchone()
  if not s:raise ValueError('Mail requires a planned armed ship, active gunner, and prepared cargo hold')
  loaded=c.execute("SELECT COALESCE(sum(placement.quantity*definition.mass_grams),0)/1000000.0 FROM inv_container_lot placement JOIN inv_lot lot USING(lot_id) JOIN inv_item_definition definition ON definition.rule_id=lot.item_rule_id WHERE placement.container_id=%s",(s[7],)).fetchone()[0];reserved=c.execute("SELECT COALESCE(sum(reserved_tons),0) FROM ship_cargo_reservation WHERE ship_id=%s AND reservation_status='reserved'",(s[3],)).fetchone()[0]
  if loaded+reserved+5>s[5]:raise ValueError(f'Postal duty requires 5 free cargo tons; only {s[5]-loaded-reserved} remain')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('accept_postal_contract',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();roll=(random_source or secrets.SystemRandom()).randint(1,6);c.execute("INSERT INTO cmd_random_draw VALUES(%s,'postal_contract',1,6,%s)",(cid,roll));reservation=c.execute("INSERT INTO ship_cargo_reservation(ship_id,campaign_id,journey_id,reservation_kind,reserved_tons) VALUES(%s,%s,%s,'postal-duty',5) RETURNING cargo_reservation_id",(s[3],s[0],s[1])).fetchone()[0]
  contract,contract_pub=c.execute("INSERT INTO journey_postal_contract(campaign_id,journey_id,journey_leg_id,ship_id,cargo_reservation_id,gunner_crew_assignment_id,actual_mail_natural_roll,actual_mail_tons,reserved_mail_tons,promised_payment_credits,source_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,5,25000,%s) RETURNING postal_contract_id,public_id",(s[0],s[1],s[2],s[3],reservation,s[6],roll,roll-1,cid)).fetchone();c.execute("INSERT INTO cmd_postal_contract_acceptance_receipt VALUES(%s,%s,%s,%s,%s,%s,5,25000)",(cid,s[0],contract,s[1],s[3],roll-1));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'postal_contract_accepted')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _accept(c,cid,pub,False)
def deliver_postal_contract_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,contract_public_id:str,actor_public_id:str)->PostalDeliveryResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('deliver_postal_contract','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _deliver(c,old[0],old[1],True)
  s=c.execute("SELECT contract.campaign_id,contract.postal_contract_id,contract.ship_id,ship.public_id,contract.actual_mail_tons,contract.promised_payment_credits,leg.destination_location_id,clock.day_number,actor.actor_id,setup.trader_account_id,balance.balance_minor FROM journey_postal_contract contract JOIN camp_campaign campaign USING(campaign_id) JOIN camp_clock clock USING(campaign_id) JOIN journey_journey journey USING(journey_id) JOIN journey_leg leg ON leg.journey_leg_id=contract.journey_leg_id JOIN ship_ship ship ON ship.ship_id=contract.ship_id AND ship.current_location_id=leg.destination_location_id JOIN actor_actor actor ON actor.campaign_id=contract.campaign_id AND actor.public_id=%s JOIN cmd_trading_preparation_receipt setup ON setup.campaign_id=contract.campaign_id AND setup.actor_id=actor.actor_id AND setup.ship_id=ship.ship_id JOIN fin_account_balance balance ON balance.account_id=setup.trader_account_id WHERE contract.public_id=%s AND campaign.owner_reference=%s AND journey.journey_status='completed' AND NOT EXISTS(SELECT 1 FROM journey_postal_delivery_receipt delivery WHERE delivery.postal_contract_id=contract.postal_contract_id) FOR UPDATE OF contract,journey,ship,actor",(actor_public_id,contract_public_id,initiator_reference)).fetchone()
  if not s:raise ValueError('Mail can only be delivered by its ship after arrival at the contracted destination')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('deliver_postal_contract',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();customer=c.execute("SELECT account_id FROM fin_account WHERE campaign_id=%s AND account_code='postal-service'",(s[0],)).fetchone()
  if customer:customer=customer[0]
  else:customer=c.execute("INSERT INTO fin_account(campaign_id,currency_code,account_code,name,account_kind) VALUES(%s,'CR','postal-service','Postal Service','external') RETURNING account_id",(s[0],)).fetchone()[0];c.execute("INSERT INTO fin_external_account VALUES(%s,%s,'Postal authority')",(customer,s[0]))
  tx=c.execute("INSERT INTO fin_transaction(campaign_id,currency_code,description,command_id) VALUES(%s,'CR','Postal delivery',%s) RETURNING transaction_id",(s[0],cid)).fetchone()[0];c.execute("INSERT INTO fin_entry(transaction_id,campaign_id,currency_code,account_id,entry_order,amount_minor) VALUES(%s,%s,'CR',%s,1,%s),(%s,%s,'CR',%s,2,%s)",(tx,s[0],s[9],s[5],tx,s[0],customer,-s[5]));c.execute("SELECT fin_post_transaction(%s)",(tx,));c.execute("INSERT INTO journey_postal_delivery_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,clock_timestamp(),%s)",(s[1],s[0],s[6],s[4],s[5],tx,s[7],cid));after=s[10]+s[5];c.execute("INSERT INTO cmd_postal_contract_delivery_receipt VALUES(%s,%s,%s,%s,%s,%s)",(cid,s[0],s[1],s[8],tx,after));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'postal_contract_delivered')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _deliver(c,cid,pub,False)
