"""Source-adjudicated 480-month ship mortgage lifecycle."""
from dataclasses import dataclass
import math
import psycopg
@dataclass(frozen=True)
class MortgageOpeningResult:
 command_public_id:str;ship_public_id:str;cash_price:int;monthly_payment:int;term_months:int;next_due_day:int;replayed:bool
@dataclass(frozen=True)
class MortgagePaymentResult:
 command_public_id:str;ship_public_id:str;payment_number:int;amount:int;balance_after:int;next_due_day:int|None;status:str;replayed:bool
def _open(c,cid,pub,replayed):
 r=c.execute("SELECT ship.public_id,receipt.cash_price_minor,receipt.payment_amount_minor,receipt.term_months,receipt.next_due_day FROM cmd_ship_mortgage_opening_receipt receipt JOIN ship_ship ship USING(ship_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return MortgageOpeningResult(str(pub),str(r[0]),r[1],r[2],r[3],r[4],replayed)
def _pay(c,cid,pub,replayed):
 r=c.execute("SELECT ship.public_id,receipt.payment_number,receipt.amount_minor,receipt.balance_after_minor,receipt.next_due_day,receipt.mortgage_status FROM cmd_ship_mortgage_payment_receipt receipt JOIN ship_mortgage mortgage USING(ship_mortgage_id) JOIN ship_ship ship USING(ship_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return MortgagePaymentResult(str(pub),str(r[0]),r[1],r[2],r[3],r[4],r[5],replayed)
def open_ship_mortgage_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,campaign_public_id:str,ship_public_id:str,actor_public_id:str)->MortgageOpeningResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('open_ship_mortgage','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _open(c,old[0],old[1],True)
  s=c.execute("SELECT campaign.campaign_id,ship.ship_id,class.construction_cost_minor,actor.actor_id,setup.trader_account_id,clock.day_number FROM camp_campaign campaign JOIN ship_ship ship USING(campaign_id) JOIN ship_class class USING(ship_class_rule_id) JOIN actor_actor actor ON actor.campaign_id=campaign.campaign_id AND actor.public_id=%s JOIN cmd_trading_preparation_receipt setup ON setup.campaign_id=campaign.campaign_id AND setup.ship_id=ship.ship_id AND setup.actor_id=actor.actor_id JOIN camp_clock clock USING(campaign_id) WHERE campaign.public_id=%s AND campaign.owner_reference=%s AND ship.public_id=%s AND NOT EXISTS(SELECT 1 FROM ship_mortgage mortgage WHERE mortgage.ship_id=ship.ship_id AND mortgage.mortgage_status IN('current','delinquent','defaulted')) FOR UPDATE OF ship,actor",(actor_public_id,campaign_public_id,initiator_reference,ship_public_id)).fetchone()
  if not s:raise ValueError('Mortgage requires a controlled ship with a prepared owner account and no active financing')
  cash=s[2];payment=math.ceil(cash/240);total=payment*480;cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('open_ship_mortgage',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();bank=c.execute("INSERT INTO fin_account(campaign_id,currency_code,account_code,name,account_kind) VALUES(%s,'CR',%s,%s,'external') RETURNING account_id",(s[0],f'mortgage-bank-{s[1]}',f'Mortgage Bank: ship {s[1]}')).fetchone()[0];c.execute("INSERT INTO fin_external_account VALUES(%s,%s,'Ship mortgage lender')",(bank,s[0]));interest=c.execute("INSERT INTO ship_legal_interest(ship_id,campaign_id,interest_kind,account_id,source_command_id) VALUES(%s,%s,'mortgage',%s,%s) RETURNING legal_interest_id",(s[1],s[0],bank,cid)).fetchone()[0];obligation=c.execute("INSERT INTO fin_obligation(campaign_id,currency_code,debtor_account_id,creditor_account_id,principal_minor,obligation_kind,description,due_day,due_second,source_command_id) VALUES(%s,'CR',%s,%s,%s,'mortgage','Ship mortgage',%s,0,%s) RETURNING obligation_id",(s[0],s[4],bank,total,s[5]+30,cid)).fetchone()[0];mortgage=c.execute("INSERT INTO ship_mortgage(ship_id,campaign_id,legal_interest_id,obligation_id,operating_cost_code,cash_price_minor,financed_principal_minor,total_financed_minor,payment_amount_minor,term_months,opened_day,next_due_day,source_command_id) VALUES(%s,%s,%s,%s,'mortgage-standard',%s,%s,%s,%s,480,%s,%s,%s) RETURNING ship_mortgage_id",(s[1],s[0],interest,obligation,cash,cash,total,payment,s[5],s[5]+30,cid)).fetchone()[0];c.execute("INSERT INTO cmd_ship_mortgage_opening_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,480,%s)",(cid,s[0],mortgage,s[1],s[3],cash,payment,s[5]+30));c.execute("INSERT INTO cmd_domain_event VALUES(%s,1,'ship_mortgage_opened')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _open(c,cid,pub,False)
def pay_ship_mortgage_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,ship_public_id:str,actor_public_id:str)->MortgagePaymentResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('pay_ship_mortgage','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _pay(c,old[0],old[1],True)
  s=c.execute("SELECT mortgage.campaign_id,mortgage.ship_mortgage_id,mortgage.legal_interest_id,mortgage.obligation_id,mortgage.payment_amount_minor,mortgage.payments_made,mortgage.term_months,mortgage.next_due_day,clock.day_number,actor.actor_id,setup.trader_account_id,balance.balance_minor,obligation.creditor_account_id FROM ship_mortgage mortgage JOIN camp_campaign campaign USING(campaign_id) JOIN ship_ship ship USING(ship_id) JOIN camp_clock clock USING(campaign_id) JOIN actor_actor actor ON actor.campaign_id=mortgage.campaign_id AND actor.public_id=%s JOIN cmd_trading_preparation_receipt setup ON setup.campaign_id=mortgage.campaign_id AND setup.ship_id=ship.ship_id AND setup.actor_id=actor.actor_id JOIN fin_account_balance balance ON balance.account_id=setup.trader_account_id JOIN fin_obligation obligation USING(obligation_id) WHERE ship.public_id=%s AND campaign.owner_reference=%s AND mortgage.mortgage_status='current' FOR UPDATE OF mortgage,ship,actor,obligation",(actor_public_id,ship_public_id,initiator_reference)).fetchone()
  if not s:raise ValueError('Current controlled ship mortgage and payer account are required')
  if s[8]<s[7]:raise ValueError(f'Mortgage payment is not due until campaign day {s[7]}')
  if s[11]<s[4]:raise ValueError('Insufficient ship account balance for mortgage payment')
  number=s[5]+1;final=number==s[6];cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('pay_ship_mortgage',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();tx=c.execute("INSERT INTO fin_transaction(campaign_id,currency_code,description,command_id) VALUES(%s,'CR',%s,%s) RETURNING transaction_id",(s[0],f'Ship mortgage payment {number}',cid)).fetchone()[0];c.execute("INSERT INTO fin_entry(transaction_id,campaign_id,currency_code,account_id,entry_order,amount_minor) VALUES(%s,%s,'CR',%s,1,%s),(%s,%s,'CR',%s,2,%s)",(tx,s[0],s[10],-s[4],tx,s[0],s[12],s[4]));c.execute("SELECT fin_post_transaction(%s)",(tx,));c.execute("INSERT INTO fin_obligation_payment(obligation_id,transaction_id,campaign_id,currency_code,amount_minor) VALUES(%s,%s,%s,'CR',%s)",(s[3],tx,s[0],s[4]));next_due=None if final else s[7]+30;status='satisfied' if final else 'current';c.execute("UPDATE ship_mortgage SET payments_made=%s,next_due_day=%s,mortgage_status=%s,ended_day=CASE WHEN %s THEN %s END WHERE ship_mortgage_id=%s",(number,next_due,status,final,s[8],s[1]));
  if final:c.execute("UPDATE fin_obligation SET obligation_status='satisfied',ended_at=clock_timestamp() WHERE obligation_id=%s",(s[3],));c.execute("UPDATE ship_legal_interest SET ended_at=clock_timestamp() WHERE legal_interest_id=%s",(s[2],))
  after=s[11]-s[4];c.execute("INSERT INTO cmd_ship_mortgage_payment_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s)",(cid,s[0],s[1],number,s[4],tx,after,next_due,status));c.execute("INSERT INTO cmd_domain_event VALUES(%s,1,%s)",(cid,'ship_mortgage_satisfied' if final else 'ship_mortgage_paid'));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _pay(c,cid,pub,False)
