"""Private source verification and explicit spoiler-safe publication boundaries."""
import psycopg
def review_campaign_source_page_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,document_public_id:str,page_number:int,text_verified:bool,visual_verified:bool,generic_issue_code:str|None=None,private_review_note:str=''):
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:return str(old[1])
  page=c.execute("SELECT document.campaign_id,document.source_document_id,page.visual_review_required,COALESCE(max(review.review_order),0)+1 FROM camp_source_document document JOIN camp_campaign campaign USING(campaign_id) JOIN camp_source_page page USING(source_document_id,campaign_id) LEFT JOIN camp_source_page_review review USING(source_document_id,campaign_id,page_number) WHERE document.public_id=%s AND page.page_number=%s AND campaign.owner_reference=%s GROUP BY document.campaign_id,document.source_document_id,page.visual_review_required",(document_public_id,page_number,initiator_reference)).fetchone()
  if not page:raise ValueError('Campaign source page does not exist')
  if page[2] and text_verified and not visual_verified and not generic_issue_code:generic_issue_code='visual_check_required'
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('review_campaign_source_page',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();review=c.execute("INSERT INTO camp_source_page_review(source_document_id,campaign_id,page_number,review_order,reviewer_kind,text_verified,visual_verified,generic_issue_code,private_review_note,source_command_id) VALUES(%s,%s,%s,%s,'ai_referee',%s,%s,%s,%s,%s) RETURNING source_page_review_id",(page[1],page[0],page_number,page[3],text_verified,visual_verified,generic_issue_code,private_review_note,cid)).fetchone()[0];state='verified' if text_verified and (not page[2] or visual_verified) else 'rejected';c.execute("INSERT INTO cmd_campaign_source_page_review_receipt VALUES(%s,%s,%s,%s,%s,%s)",(cid,page[0],review,page[1],page_number,state));c.execute("INSERT INTO cmd_domain_event VALUES(%s,1,'campaign_source_page_reviewed')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return str(pub)
def publish_campaign_source_intro_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,document_public_id:str,introduction_text:str):
 with c.transaction():
  document=c.execute("SELECT document.source_document_id,document.campaign_id FROM camp_source_document document JOIN camp_campaign campaign USING(campaign_id) WHERE document.public_id=%s AND campaign.owner_reference=%s",(document_public_id,initiator_reference)).fetchone()
  if not document:raise ValueError('Campaign source does not exist')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('publish_campaign_source_intro',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();c.execute("INSERT INTO camp_source_player_intro VALUES(%s,%s,%s,clock_timestamp(),%s)",(document[0],document[1],introduction_text.strip(),cid));c.execute("INSERT INTO cmd_campaign_source_intro_receipt VALUES(%s,%s,%s)",(cid,document[1],document[0]));c.execute("INSERT INTO cmd_domain_event VALUES(%s,1,'campaign_source_intro_published')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return str(pub)
def reveal_campaign_source_excerpt_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,document_public_id:str,page_number:int,excerpt_text:str,reveal_reason:str):
 with c.transaction():
  page=c.execute("SELECT document.source_document_id,document.campaign_id,page.text_content,clock.day_number FROM camp_source_document document JOIN camp_campaign campaign USING(campaign_id) JOIN camp_clock clock USING(campaign_id) JOIN camp_source_page page USING(source_document_id,campaign_id) WHERE document.public_id=%s AND page.page_number=%s AND campaign.owner_reference=%s AND document.ingestion_status='ready'",(document_public_id,page_number,initiator_reference)).fetchone()
  if not page:raise ValueError('Only a verified source page may be revealed')
  excerpt=excerpt_text.strip()
  if not excerpt or excerpt not in page[2]:raise ValueError('Revealed text must be an exact excerpt from the verified page')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('reveal_campaign_source_excerpt',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();revealed=c.execute("INSERT INTO camp_source_revealed_excerpt(source_document_id,campaign_id,page_number,excerpt_text,reveal_reason,revealed_day,source_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s) RETURNING revealed_excerpt_id",(page[0],page[1],page_number,excerpt,reveal_reason.strip(),page[3],cid)).fetchone()[0];c.execute("INSERT INTO cmd_campaign_source_reveal_receipt VALUES(%s,%s,%s,%s,%s)",(cid,page[1],revealed,page[0],page_number));c.execute("INSERT INTO cmd_domain_event VALUES(%s,1,'campaign_source_excerpt_revealed')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return str(pub)
