"""Immutable starship charter quotations, acceptance, and settlement."""
from dataclasses import dataclass
import psycopg
@dataclass(frozen=True)
class CharterQuoteResult:
 command_public_id:str;quote_public_id:str;ship_public_id:str;billing_blocks:int;quoted_price:int;replayed:bool
@dataclass(frozen=True)
class CharterContractResult:
 command_public_id:str;contract_public_id:str;quote_public_id:str;journey_public_id:str;ship_public_id:str;promised_payment:int;replayed:bool
@dataclass(frozen=True)
class CharterCompletionResult:
 command_public_id:str;contract_public_id:str;ship_public_id:str;paid_credits:int;balance_after:int;replayed:bool
def _quote(c,cid,pub,replayed):
 r=c.execute("SELECT quote.public_id,ship.public_id,receipt.billing_blocks,receipt.quoted_price_credits FROM cmd_starship_charter_quote_receipt receipt JOIN journey_starship_charter_quote_receipt quote USING(charter_quote_id) JOIN ship_ship ship USING(ship_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return CharterQuoteResult(str(pub),str(r[0]),str(r[1]),r[2],r[3],replayed)
def _contract(c,cid,pub,replayed):
 r=c.execute("SELECT contract.public_id,quote.public_id,journey.public_id,ship.public_id,receipt.promised_payment_credits FROM cmd_starship_charter_acceptance_receipt receipt JOIN journey_starship_charter_contract contract USING(charter_contract_id) JOIN journey_starship_charter_quote_receipt quote USING(charter_quote_id) JOIN journey_journey journey USING(journey_id) JOIN ship_ship ship USING(ship_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return CharterContractResult(str(pub),str(r[0]),str(r[1]),str(r[2]),str(r[3]),r[4],replayed)
def _complete(c,cid,pub,replayed):
 r=c.execute("SELECT contract.public_id,ship.public_id,completion.paid_credits,receipt.balance_after_minor FROM cmd_starship_charter_completion_receipt receipt JOIN journey_starship_charter_contract contract USING(charter_contract_id) JOIN ship_ship ship USING(ship_id) JOIN journey_starship_charter_completion_receipt completion USING(charter_contract_id) WHERE receipt.command_id=%s",(cid,)).fetchone();return CharterCompletionResult(str(pub),str(r[0]),str(r[1]),r[2],r[3],replayed)
def quote_starship_charter_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,campaign_public_id:str,ship_public_id:str,billing_blocks:int)->CharterQuoteResult:
 if billing_blocks<=0:raise ValueError('Charter billing blocks must be positive')
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('quote_starship_charter','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _quote(c,old[0],old[1],True)
  s=c.execute("SELECT campaign.campaign_id,ship.ship_id,ship.ship_class_rule_id,class.cargo_capacity_tons,COALESCE(high.characteristic_value,0)::integer,COALESCE(low.characteristic_value,0)::integer,rate.cargo_ton_rate_credits,rate.high_berth_rate_credits,rate.low_berth_rate_credits,rate.owner_pays_overhead,rate.owner_supplies_crew FROM camp_campaign campaign JOIN ship_ship ship USING(campaign_id) JOIN ship_class class USING(ship_class_rule_id) LEFT JOIN ship_class_characteristic high ON high.ship_class_rule_id=class.ship_class_rule_id AND high.characteristic_code='staterooms' LEFT JOIN ship_class_characteristic low ON low.ship_class_rule_id=class.ship_class_rule_id AND low.characteristic_code='low_berths' JOIN rule_ship_charter_rate rate ON rate.charter_kind='starship' WHERE campaign.public_id=%s AND campaign.owner_reference=%s AND ship.public_id=%s AND ship.lifecycle_status='active' FOR UPDATE OF ship",(campaign_public_id,initiator_reference,ship_public_id)).fetchone()
  if not s:raise ValueError('Active controlled ship does not exist')
  price=billing_blocks*(s[3]*s[6]+s[4]*s[7]+s[5]*s[8]);cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('quote_starship_charter',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();quote,qpub=c.execute("INSERT INTO journey_starship_charter_quote_receipt(campaign_id,ship_id,ship_class_rule_id,cargo_capacity_tons_snapshot,high_berths_snapshot,low_berths_snapshot,billing_blocks,cargo_rate_credits,high_berth_rate_credits,low_berth_rate_credits,quoted_price_credits,owner_pays_overhead,owner_supplies_crew,source_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING charter_quote_id,public_id",(s[0],s[1],s[2],s[3],s[4],s[5],billing_blocks,s[6],s[7],s[8],price,s[9],s[10],cid)).fetchone();c.execute("INSERT INTO cmd_starship_charter_quote_receipt VALUES(%s,%s,%s,%s,%s,%s)",(cid,s[0],quote,s[1],billing_blocks,price));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'starship_charter_quoted')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _quote(c,cid,pub,False)
def accept_starship_charter_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,quote_public_id:str,journey_public_id:str)->CharterContractResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('accept_starship_charter','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _contract(c,old[0],old[1],True)
  s=c.execute("SELECT quote.campaign_id,quote.charter_quote_id,journey.journey_id,quote.ship_id,quote.quoted_price_credits,clock.day_number FROM journey_starship_charter_quote_receipt quote JOIN camp_campaign campaign USING(campaign_id) JOIN camp_clock clock USING(campaign_id) JOIN journey_journey journey ON journey.public_id=%s AND journey.campaign_id=quote.campaign_id AND journey.ship_id=quote.ship_id WHERE quote.public_id=%s AND campaign.owner_reference=%s AND journey.journey_status='planning' AND NOT EXISTS(SELECT 1 FROM journey_starship_charter_contract contract WHERE contract.charter_quote_id=quote.charter_quote_id OR contract.journey_id=journey.journey_id) FOR UPDATE OF quote,journey",(journey_public_id,quote_public_id,initiator_reference)).fetchone()
  if not s:raise ValueError('Available charter quote and planning journey must use the same ship')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('accept_starship_charter',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();contract,cpub=c.execute("INSERT INTO journey_starship_charter_contract(campaign_id,charter_quote_id,journey_id,ship_id,promised_payment_credits,accepted_day,source_command_id) VALUES(%s,%s,%s,%s,%s,%s,%s) RETURNING charter_contract_id,public_id",(s[0],s[1],s[2],s[3],s[4],s[5],cid)).fetchone();c.execute("INSERT INTO cmd_starship_charter_acceptance_receipt VALUES(%s,%s,%s,%s,%s,%s,%s)",(cid,s[0],contract,s[1],s[2],s[3],s[4]));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'starship_charter_accepted')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _contract(c,cid,pub,False)
def complete_starship_charter_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,contract_public_id:str,actor_public_id:str)->CharterCompletionResult:
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('complete_starship_charter','completed'):raise RuntimeError('Idempotency key belongs to another command')
   return _complete(c,old[0],old[1],True)
  s=c.execute("SELECT contract.campaign_id,contract.charter_contract_id,contract.ship_id,ship.public_id,contract.promised_payment_credits,clock.day_number,actor.actor_id,setup.trader_account_id,balance.balance_minor FROM journey_starship_charter_contract contract JOIN camp_campaign campaign USING(campaign_id) JOIN camp_clock clock USING(campaign_id) JOIN journey_journey journey USING(journey_id) JOIN ship_ship ship USING(ship_id) JOIN actor_actor actor ON actor.campaign_id=contract.campaign_id AND actor.public_id=%s JOIN cmd_trading_preparation_receipt setup ON setup.campaign_id=contract.campaign_id AND setup.actor_id=actor.actor_id AND setup.ship_id=ship.ship_id JOIN fin_account_balance balance ON balance.account_id=setup.trader_account_id WHERE contract.public_id=%s AND campaign.owner_reference=%s AND journey.journey_status='completed' AND NOT EXISTS(SELECT 1 FROM journey_starship_charter_completion_receipt completion WHERE completion.charter_contract_id=contract.charter_contract_id) FOR UPDATE OF contract,journey,ship,actor",(actor_public_id,contract_public_id,initiator_reference)).fetchone()
  if not s:raise ValueError('Charter payment requires its completed journey and prepared ship account')
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('complete_starship_charter',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();customer=c.execute("SELECT account_id FROM fin_account WHERE campaign_id=%s AND account_code='charter-customers'",(s[0],)).fetchone()
  if customer:customer=customer[0]
  else:customer=c.execute("INSERT INTO fin_account(campaign_id,currency_code,account_code,name,account_kind) VALUES(%s,'CR','charter-customers','Charter Customers','external') RETURNING account_id",(s[0],)).fetchone()[0];c.execute("INSERT INTO fin_external_account VALUES(%s,%s,'Charter customers')",(customer,s[0]))
  tx=c.execute("INSERT INTO fin_transaction(campaign_id,currency_code,description,command_id) VALUES(%s,'CR','Starship charter completion',%s) RETURNING transaction_id",(s[0],cid)).fetchone()[0];c.execute("INSERT INTO fin_entry(transaction_id,campaign_id,currency_code,account_id,entry_order,amount_minor) VALUES(%s,%s,'CR',%s,1,%s),(%s,%s,'CR',%s,2,%s)",(tx,s[0],s[7],s[4],tx,s[0],customer,-s[4]));c.execute("SELECT fin_post_transaction(%s)",(tx,));c.execute("INSERT INTO journey_starship_charter_completion_receipt VALUES(%s,%s,%s,%s,%s,clock_timestamp(),%s)",(s[1],s[0],s[4],tx,s[5],cid));after=s[8]+s[4];c.execute("INSERT INTO cmd_starship_charter_completion_receipt VALUES(%s,%s,%s,%s,%s,%s)",(cid,s[0],s[1],s[6],tx,after));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'starship_charter_completed')",(cid,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return _complete(c,cid,pub,False)
