"""Journey-bound Steward service task resolutions."""
from dataclasses import dataclass
import psycopg
from engine.tasks import resolve_actor_task_command
@dataclass(frozen=True)
class StewardResult:
 command_public_id:str;journey_public_id:str;steward_actor_public_id:str;passenger_actor_public_id:str;service_code:str;service_reference:str;check_total:int;effect:int;succeeded:bool;replayed:bool
def resolve_steward_service_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,journey_public_id:str,steward_actor_public_id:str,passenger_actor_public_id:str,service_code:str,service_reference:str,characteristic_rule_code:str,difficulty_rule_code:str,random_source=None)->StewardResult:
 if not service_reference.strip():raise ValueError('Steward service reference is required')
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('resolve_steward_service','completed'):raise RuntimeError('Idempotency key belongs to another command')
   r=c.execute("SELECT j.public_id,s.public_id,p.public_id,x.service_code,x.service_reference,x.check_total,x.effect,x.succeeded FROM cmd_steward_service_receipt x JOIN journey_journey j USING(journey_id) JOIN actor_actor s ON s.actor_id=x.steward_actor_id JOIN actor_actor p ON p.actor_id=x.passenger_actor_id WHERE x.command_id=%s",(old[0],)).fetchone();return StewardResult(str(old[1]),str(r[0]),str(r[1]),str(r[2]),r[3],r[4],r[5],r[6],r[7],True)
  state=c.execute("SELECT j.journey_id,j.campaign_id,s.actor_id,p.actor_id,m.rule_id,passage.passage_class FROM journey_journey j JOIN journey_participant crew ON crew.journey_id=j.journey_id AND crew.campaign_id=j.campaign_id AND crew.participant_role='crew' AND crew.commitment_status IN('planned','committed') JOIN actor_actor s ON s.actor_id=crew.actor_id AND s.public_id=%s AND s.controller_reference=%s JOIN journey_passage passage ON passage.journey_id=j.journey_id AND passage.campaign_id=j.campaign_id AND passage.passage_class='high' AND passage.passage_status IN('booked','boarded') JOIN actor_actor p ON p.actor_id=passage.actor_id AND p.public_id=%s JOIN rule_steward_mechanic m ON true JOIN rule_steward_service service ON service.rule_id=m.rule_id AND service.service_code=%s WHERE j.public_id=%s AND j.journey_status IN('planning','ready','underway') FOR UPDATE OF j,crew,s,passage,p",(steward_actor_public_id,initiator_reference,passenger_actor_public_id,service_code,journey_public_id)).fetchone()
  if not state:raise ValueError('Steward service requires controlled journey crew and a high-passage recipient')
  task=resolve_actor_task_command(c,initiator_reference=initiator_reference,idempotency_key=f'steward:{idempotency_key}',actor_public_id=steward_actor_public_id,characteristic_rule_code=characteristic_rule_code,skill_rule_code='skill.steward',difficulty_rule_code=difficulty_rule_code,random_source=random_source);task_id=c.execute("SELECT command_id FROM cmd_command WHERE public_id=%s",(task.command_public_id,)).fetchone()[0];cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('resolve_steward_service',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone();c.execute("INSERT INTO cmd_steward_service_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(cid,state[1],state[0],state[2],state[3],state[4],service_code,service_reference.strip(),state[5],task_id,task.total,task.effect,task.succeeded));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return StewardResult(str(pub),journey_public_id,steward_actor_public_id,passenger_actor_public_id,service_code,service_reference.strip(),task.total,task.effect,task.succeeded,False)
