"""Crew-bound spacecraft and vehicle operation commands."""
from dataclasses import dataclass
import psycopg
from engine.tasks import resolve_actor_task_command
@dataclass(frozen=True)
class TransportResult:
 command_public_id:str;actor_public_id:str;target_public_id:str;target_kind:str;skill_rule_code:str;operation_kind:str;challenging_conditions:bool;automatic_success:bool;check_total:int|None;effect:int|None;succeeded:bool;replayed:bool
def resolve_transport_operation_command(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,actor_public_id:str,target_public_id:str,target_kind:str,operation_kind:str,operation_reference:str,challenging_conditions:bool,characteristic_rule_code:str,difficulty_rule_code:str,random_source=None)->TransportResult:
 if target_kind not in ('vehicle','ship') or not operation_reference.strip():raise ValueError('Transport target and operation reference are required')
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2:]!=('resolve_transport_operation','completed'):raise RuntimeError('Idempotency key belongs to another command')
   r=c.execute("SELECT a.public_id,COALESCE(v.public_id,s.public_id),x.target_kind,skill.rule_code,x.operation_kind,x.challenging_conditions,x.automatic_success,x.check_total,x.effect,x.succeeded FROM cmd_transport_operation_receipt x JOIN actor_actor a ON a.actor_id=x.actor_id JOIN rule_rule skill ON skill.rule_id=x.skill_rule_id LEFT JOIN vehicle_vehicle v ON v.vehicle_id=x.vehicle_id LEFT JOIN ship_ship s ON s.ship_id=x.ship_id WHERE x.command_id=%s",(old[0],)).fetchone();return TransportResult(str(old[1]),str(r[0]),str(r[1]),r[2],r[3],r[4],r[5],r[6],r[7],r[8],r[9],True)
  if target_kind=='vehicle':state=c.execute("SELECT a.actor_id,v.campaign_id,m.rule_id,p.operating_skill_rule_id,v.vehicle_id,NULL::bigint FROM actor_actor a JOIN vehicle_crew_assignment ca ON ca.actor_id=a.actor_id AND ca.duty_status='active' JOIN vehicle_vehicle v ON v.vehicle_id=ca.vehicle_id AND v.campaign_id=a.campaign_id AND v.public_id=%s AND v.lifecycle_status IN('active','disabled') JOIN rule_book1_vehicle_profile p ON p.vehicle_class_rule_id=v.vehicle_class_rule_id JOIN rule_transport_operation_mechanic m ON true JOIN rule_transport_skill_capability cap ON cap.rule_id=m.rule_id AND cap.skill_rule_id=p.operating_skill_rule_id AND cap.target_kind='vehicle' WHERE a.public_id=%s AND a.controller_reference=%s FOR UPDATE OF a,ca,v",(target_public_id,actor_public_id,initiator_reference)).fetchone()
  else:state=c.execute("SELECT a.actor_id,s.campaign_id,m.rule_id,cap.skill_rule_id,NULL::bigint,s.ship_id FROM actor_actor a JOIN ship_crew_assignment ca ON ca.actor_id=a.actor_id AND ca.duty_status='active' JOIN ship_ship s ON s.ship_id=ca.ship_id AND s.campaign_id=a.campaign_id AND s.public_id=%s AND s.lifecycle_status='active' JOIN ship_crew_position pos ON pos.ship_crew_position_id=ca.ship_crew_position_id JOIN ship_crew_position_definition def ON def.crew_position_rule_id=pos.crew_position_rule_id AND def.position_code='pilot' JOIN rule_transport_operation_mechanic m ON true JOIN rule_transport_skill_capability cap ON cap.rule_id=m.rule_id AND cap.target_kind='ship' WHERE a.public_id=%s AND a.controller_reference=%s FOR UPDATE OF a,ca,s",(target_public_id,actor_public_id,initiator_reference)).fetchone()
  if not state:raise ValueError('Transport operation requires the matching active crew assignment')
  skill=c.execute("SELECT rule_code FROM rule_rule WHERE rule_id=%s",(state[3],)).fetchone()[0];automatic=target_kind=='ship' and not challenging_conditions;task_id=total=effect=None;succeeded=True
  cid,pub=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('resolve_transport_operation',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone()
  if not automatic:
   task=resolve_actor_task_command(c,initiator_reference=initiator_reference,idempotency_key=f'transport:{idempotency_key}',actor_public_id=actor_public_id,characteristic_rule_code=characteristic_rule_code,skill_rule_code=skill,difficulty_rule_code=difficulty_rule_code,random_source=random_source);task_id=c.execute("SELECT command_id FROM cmd_command WHERE public_id=%s",(task.command_public_id,)).fetchone()[0];total,effect,succeeded=task.total,task.effect,task.succeeded
  c.execute("INSERT INTO cmd_transport_operation_receipt VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(cid,state[1],state[0],state[2],state[3],target_kind,state[4],state[5],operation_kind,operation_reference.strip(),challenging_conditions,automatic,task_id,total,effect,succeeded));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(cid,));return TransportResult(str(pub),actor_public_id,target_public_id,target_kind,skill,operation_kind,challenging_conditions,automatic,total,effect,succeeded,False)
