import os,unittest,uuid
import psycopg
from engine.spacecraft_journeys import start_spacecraft_journey_leg_command,complete_spacecraft_journey_leg_command
@unittest.skipUnless(os.environ.get('BASE_CEPHEUS_DATABASE_URL'),'requires PostgreSQL')
class SpacecraftJourneyExecutionTests(unittest.TestCase):
 def rule(self,c,code,name,category):return c.execute("INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status) SELECT content_package_id,%s,%s,%s,'approved' FROM sys_content_package WHERE package_code='cepheus-engine' RETURNING rule_id",(code,name,category)).fetchone()[0]
 def location(self,c,camp,suffix):
  r=self.rule(c,'location.test.'+suffix+uuid.uuid4().hex,'Location '+suffix,'world');c.execute("INSERT INTO rule_location_type VALUES(%s,%s,true,true)",(r,'test-'+suffix+'-'+uuid.uuid4().hex));return c.execute("INSERT INTO loc_location(campaign_id,location_type_rule_id,name) VALUES(%s,%s,%s) RETURNING location_id",(camp,r,suffix)).fetchone()[0]
 def test_normal_leg_consumes_plan_advances_clock_and_moves_ship(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   with c.transaction(force_rollback=True):
    camp=c.execute("INSERT INTO camp_campaign(name,owner_reference) VALUES(%s,'ref') RETURNING campaign_id",(str(uuid.uuid4()),)).fetchone()[0];c.execute("INSERT INTO camp_clock(campaign_id,day_number,second_of_day) VALUES(%s,4,80000) ON CONFLICT(campaign_id) DO UPDATE SET day_number=4,second_of_day=80000",(camp,));origin=self.location(c,camp,'origin');dest=self.location(c,camp,'destination');item_rule=self.rule(c,'item.ship.'+uuid.uuid4().hex,'Ship Item','equipment');c.execute("INSERT INTO inv_item_definition(rule_id,item_kind,minimum_tech_level,cost_credits) VALUES(%s,'equipment',9,1)",(item_rule,));item=c.execute("INSERT INTO inv_item_instance(campaign_id,item_rule_id,instance_name) VALUES(%s,%s,'Ship') RETURNING item_instance_id",(camp,item_rule)).fetchone()[0];class_rule=self.rule(c,'ship.class.'+uuid.uuid4().hex,'Test Ship','ship');c.execute("INSERT INTO ship_class(ship_class_rule_id,class_code,hull_tons,hull_points,structure_points,minimum_tech_level,construction_cost_minor,jump_rating,maneuver_rating,power_rating,cargo_capacity_tons) VALUES(%s,%s,100,2,2,9,1,1,1,1,1)",(class_rule,'test-'+uuid.uuid4().hex));ship=c.execute("INSERT INTO ship_ship(campaign_id,ship_class_rule_id,inventory_item_instance_id,name,current_location_id,hull_current,structure_current) VALUES(%s,%s,%s,'Ship',%s,2,2) RETURNING ship_id",(camp,class_rule,item,origin)).fetchone()[0];c.execute("INSERT INTO ship_resource VALUES(%s,%s,'refined_fuel',10,10,clock_timestamp(),NULL)",(ship,camp));jid,jpub=c.execute("INSERT INTO journey_journey(campaign_id,journey_kind,name,ship_id) VALUES(%s,'interplanetary','Trip',%s) RETURNING journey_id,public_id",(camp,ship)).fetchone();leg=c.execute("INSERT INTO journey_leg(journey_id,campaign_id,leg_order,origin_location_id,destination_location_id,travel_mode,planned_duration_seconds) VALUES(%s,%s,1,%s,%s,'interplanetary',10000) RETURNING journey_leg_id",(jid,camp,origin,dest)).fetchone()[0];c.execute("UPDATE journey_journey SET journey_status='ready' WHERE journey_id=%s",(jid,));c.execute("INSERT INTO journey_ship_resource_plan(journey_leg_id,campaign_id,ship_id,resource_type_code,planned_quantity,plan_status) VALUES(%s,%s,%s,'refined_fuel',3,'reserved')",(leg,camp,ship))
    start=start_spacecraft_journey_leg_command(c,referee_reference='ref',idempotency_key='start',journey_public_id=str(jpub),leg_order=1);self.assertEqual(start.status,'underway');self.assertEqual(c.execute("SELECT current_quantity FROM ship_resource WHERE ship_id=%s AND resource_type_code='refined_fuel'",(ship,)).fetchone()[0],7)
    done=complete_spacecraft_journey_leg_command(c,referee_reference='ref',idempotency_key='done',journey_public_id=str(jpub),leg_order=1);self.assertTrue(done.journey_completed);self.assertEqual((done.clock_day,done.clock_second),(5,3600));self.assertEqual(c.execute("SELECT current_location_id FROM ship_ship WHERE ship_id=%s",(ship,)).fetchone()[0],dest)
