import os,unittest,psycopg
@unittest.skipUnless(os.environ.get('BASE_CEPHEUS_DATABASE_URL'),'requires PostgreSQL')
class WeatherTests(unittest.TestCase):
 def test_weather_effects_and_task_modifier_receipt(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   self.assertEqual(c.execute('SELECT visibility_ranged_attack_dm,interference_ranged_attack_dm,sensors_avoid_visibility,sensors_avoid_interference,extreme_skill_dm_min,extreme_skill_dm_max FROM rule_weather_effect').fetchone(),(-1,-1,True,False,-4,-1))
   with c.transaction(force_rollback=True):
    campaign=c.execute("INSERT INTO camp_campaign(name) VALUES('Weather test') RETURNING campaign_id").fetchone()[0];actor=c.execute("INSERT INTO actor_actor(campaign_id,name,controller_reference) VALUES(%s,'Stormwalker','test') RETURNING actor_id",(campaign,)).fetchone()[0];endurance=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='characteristic.endurance'").fetchone()[0];average=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='difficulty.average'").fetchone()[0];c.execute('INSERT INTO actor_characteristic(actor_id,characteristic_rule_id,maximum_value,current_value) VALUES(%s,%s,7,7)',(actor,endurance))
    observation=c.execute("INSERT INTO env_weather_observation(campaign_id,visibility_penalty_active,interference_penalty_active,extreme_skill_dm,campaign_day,campaign_second,observer_reference) VALUES(%s,true,true,-3,1,100,'referee') RETURNING weather_observation_id",(campaign,)).fetchone()[0];command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key,command_status,completed_at) VALUES('resolve_actor_task','test','weather-task','completed',clock_timestamp()) RETURNING command_id").fetchone()[0];c.execute('INSERT INTO cmd_actor_task_receipt(command_id,actor_id,characteristic_rule_id,skill_rule_id,difficulty_rule_id,skill_modifier,characteristic_modifier,difficulty_modifier,circumstance_modifier,species_modifier,check_total,target_number,effect,succeeded) VALUES(%s,%s,%s,NULL,%s,0,0,0,-2,0,6,8,-2,false)',(command,actor,endurance,average));c.execute('INSERT INTO env_weather_task_modifier_receipt(weather_observation_id,task_command_id,weather_modifier,other_circumstance_modifier,total_circumstance_modifier) VALUES(%s,%s,-3,1,-2)',(observation,command));self.assertEqual(c.execute('SELECT weather_modifier,other_circumstance_modifier FROM env_weather_task_modifier_receipt WHERE task_command_id=%s',(command,)).fetchone(),(-3,1))
if __name__=='__main__':unittest.main()
