import os,unittest,psycopg
@unittest.skipUnless(os.environ.get('BASE_CEPHEUS_DATABASE_URL'),'requires PostgreSQL')
class VacuumTests(unittest.TestCase):
 def test_vacuum_composition_and_exceptional_failure(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   self.assertEqual(c.execute("SELECT first_check_round_offset,exceptional_failure_effect_max,suffocation.exposure_code,radiation.source_code FROM rule_vacuum_exposure vacuum JOIN rule_suffocation_profile suffocation USING(suffocation_profile_id) JOIN rule_radiation_source_profile radiation USING(radiation_source_profile_id)").fetchone(),(2,-6,'utterly-airless','irradiated-high'))
   with c.transaction(force_rollback=True):
    campaign=c.execute("INSERT INTO camp_campaign(name) VALUES('Vacuum test') RETURNING campaign_id").fetchone()[0];actor=c.execute("INSERT INTO actor_actor(campaign_id,name,controller_reference) VALUES(%s,'Spacer','test') RETURNING actor_id",(campaign,)).fetchone()[0];endurance=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='characteristic.endurance'").fetchone()[0];difficulty=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='difficulty.very-difficult'").fetchone()[0];enc_type=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='encounter.type.routine'").fetchone()[0]
    c.execute('INSERT INTO actor_characteristic(actor_id,characteristic_rule_id,maximum_value,current_value) VALUES(%s,%s,7,7)',(actor,endurance));encounter=c.execute("INSERT INTO enc_encounter(campaign_id,encounter_type_rule_id,current_mode) VALUES(%s,%s,'personal_combat') RETURNING encounter_id",(campaign,enc_type)).fetchone()[0];c.execute('INSERT INTO enc_personal_combat(encounter_id,current_round) VALUES(%s,3)',(encounter,))
    suff_profile=c.execute("SELECT suffocation_profile_id FROM rule_suffocation_profile WHERE exposure_code='utterly-airless'").fetchone()[0];suff=c.execute('INSERT INTO env_suffocation_episode(actor_id,campaign_id,suffocation_profile_id,encounter_id,began_combat_round) VALUES(%s,%s,%s,%s,1) RETURNING suffocation_episode_id',(actor,campaign,suff_profile,encounter)).fetchone()[0];rad=c.execute("SELECT radiation_source_profile_id FROM rule_radiation_source_profile WHERE source_code='irradiated-high'").fetchone()[0];vac=c.execute('INSERT INTO env_vacuum_episode(actor_id,campaign_id,encounter_id,began_combat_round,suffocation_episode_id,radiation_source_profile_id) VALUES(%s,%s,%s,1,%s,%s) RETURNING vacuum_episode_id',(actor,campaign,encounter,suff,rad)).fetchone()[0]
    command=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key,command_status,completed_at) VALUES('resolve_actor_task','test','vacuum-fail','completed',clock_timestamp()) RETURNING command_id").fetchone()[0];c.execute('INSERT INTO cmd_actor_task_receipt(command_id,actor_id,characteristic_rule_id,skill_rule_id,difficulty_rule_id,skill_modifier,characteristic_modifier,difficulty_modifier,circumstance_modifier,species_modifier,check_total,target_number,effect,succeeded) VALUES(%s,%s,%s,NULL,%s,0,0,0,0,0,2,8,-6,false)',(command,actor,endurance,difficulty));c.execute('INSERT INTO env_vacuum_check_receipt(vacuum_episode_id,check_sequence,combat_round,task_command_id,task_succeeded,exceptional_failure,stunned_before,stunned_after,unconscious_before,unconscious_after,episode_version_before,episode_version_after) VALUES(%s,1,3,%s,false,true,false,true,false,true,1,2)',(vac,command));self.assertEqual(c.execute('SELECT stunned,unconscious FROM env_vacuum_episode WHERE vacuum_episode_id=%s',(vac,)).fetchone(),(True,True))
if __name__=='__main__':unittest.main()
