import os,unittest,uuid
import psycopg
from engine.broker_carousing import resolve_broker_operation_command,resolve_carousing_influence_command
from engine.encounters import create_encounter_command,add_encounter_participant_command,set_encounter_attitude_command
class R:
 def randint(self,a,b):return 6
@unittest.skipUnless(os.environ.get('BASE_CEPHEUS_DATABASE_URL'),'requires PostgreSQL')
class BrokerCarousingTests(unittest.TestCase):
 def actor(self,c,camp,name,controller):return c.execute("INSERT INTO actor_actor(campaign_id,name,controller_reference) VALUES(%s,%s,%s) RETURNING actor_id,public_id",(camp,name,controller)).fetchone()
 def test_broker_search_is_task_backed_and_replays(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   with c.transaction(force_rollback=True):
    camp=c.execute("INSERT INTO camp_campaign(name,owner_reference) VALUES(%s,'p') RETURNING campaign_id",(str(uuid.uuid4()),)).fetchone()[0];c.execute("INSERT INTO camp_clock(campaign_id,day_number) VALUES(%s,35) ON CONFLICT(campaign_id) DO UPDATE SET day_number=EXCLUDED.day_number",(camp,));aid,apub=self.actor(c,camp,'Broker','p');char=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='characteristic.education'").fetchone()[0];skill=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='skill.broker'").fetchone()[0];c.execute("INSERT INTO actor_characteristic VALUES(%s,%s,9,9) ON CONFLICT(actor_id,characteristic_rule_id) DO UPDATE SET maximum_value=9,current_value=9",(aid,char));c.execute("INSERT INTO actor_skill VALUES(%s,%s,2) ON CONFLICT(actor_id,skill_rule_id) DO UPDATE SET skill_level=2",(aid,skill));pkg=c.execute("SELECT content_package_id FROM sys_content_package ORDER BY content_package_id LIMIT 1").fetchone()[0];lt=c.execute("INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status) VALUES(%s,%s,'Test Port','world','approved') RETURNING rule_id",(pkg,'test.location.'+uuid.uuid4().hex)).fetchone()[0];c.execute("INSERT INTO rule_location_type VALUES(%s,%s,true,true)",(lt,'test-port-'+uuid.uuid4().hex));loc=c.execute("INSERT INTO loc_location(campaign_id,location_type_rule_id,name) VALUES(%s,%s,'Port') RETURNING location_id",(camp,lt)).fetchone()[0];market=c.execute("INSERT INTO mkt_market(campaign_id,location_id,name,market_kind) VALUES(%s,%s,'Market','legal') RETURNING market_id",(camp,loc)).fetchone()[0];session=c.execute("INSERT INTO mkt_session(market_id,campaign_id,opened_day,opened_second,expires_day,expires_second) VALUES(%s,%s,35,0,40,0) RETURNING market_session_id",(market,camp)).fetchone()[0]
    result=resolve_broker_operation_command(c,initiator_reference='p',idempotency_key='supplier',actor_public_id=str(apub),market_session_id=session,operation_code='find-supplier',objective_reference='legal cargo',characteristic_rule_code='characteristic.education',random_source=R());self.assertTrue(result.succeeded);self.assertEqual(result.attempt_number_in_month,1)
    replay=resolve_broker_operation_command(c,initiator_reference='p',idempotency_key='supplier',actor_public_id=str(apub),market_session_id=session,operation_code='find-buyer',objective_reference='changed',characteristic_rule_code='characteristic.education',random_source=R());self.assertTrue(replay.replayed);self.assertEqual(replay.operation_code,'find-supplier')
 def test_carousing_uses_actor_state_for_social_influence(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   with c.transaction(force_rollback=True):
    camp,cpub=c.execute("INSERT INTO camp_campaign(name,owner_reference) VALUES(%s,'p') RETURNING campaign_id,public_id",(str(uuid.uuid4()),)).fetchone();aid,apub=self.actor(c,camp,'Carouser','p');nid,npub=self.actor(c,camp,'Local','p');char=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='characteristic.social-standing'").fetchone()[0];skill=c.execute("SELECT rule_id FROM rule_rule WHERE rule_code='skill.carousing'").fetchone()[0];c.execute("INSERT INTO actor_characteristic VALUES(%s,%s,9,9) ON CONFLICT(actor_id,characteristic_rule_id) DO UPDATE SET maximum_value=9,current_value=9",(aid,char));c.execute("INSERT INTO actor_skill VALUES(%s,%s,2) ON CONFLICT(actor_id,skill_rule_id) DO UPDATE SET skill_level=2",(aid,skill));e=create_encounter_command(c,initiator_reference='p',idempotency_key='e',campaign_public_id=str(cpub),encounter_type_code='routine');add_encounter_participant_command(c,initiator_reference='p',idempotency_key='a',encounter_public_id=e.encounter_public_id,actor_public_id=str(apub),participant_role='player_character',side_code='party');add_encounter_participant_command(c,initiator_reference='p',idempotency_key='n',encounter_public_id=e.encounter_public_id,actor_public_id=str(npub),participant_role='non_player_character',side_code='local');set_encounter_attitude_command(c,initiator_reference='p',idempotency_key='s',encounter_public_id=e.encounter_public_id,actor_public_id=str(npub),attitude_code='indifferent')
    result=resolve_carousing_influence_command(c,initiator_reference='p',idempotency_key='c',encounter_public_id=e.encounter_public_id,acting_actor_public_id=str(apub),target_actor_public_id=str(npub),random_source=R());self.assertEqual(result.final_attitude,'friendly')
