import os,unittest,uuid
import psycopg
from engine.transport import resolve_transport_operation_command
class R:
 def randint(self,a,b):return 4
@unittest.skipUnless(os.environ.get('BASE_CEPHEUS_DATABASE_URL'),'requires PostgreSQL')
class TransportTests(unittest.TestCase):
 def test_spacecraft_routine_operation_is_automatic_but_challenge_rolls(self):
  with psycopg.connect(os.environ['BASE_CEPHEUS_DATABASE_URL']) as c:
   with c.transaction(force_rollback=True):
    camp=c.execute("INSERT INTO camp_campaign(name,owner_reference) VALUES(%s,'p') RETURNING campaign_id",(str(uuid.uuid4()),)).fetchone()[0];aid,apub=c.execute("INSERT INTO actor_actor(campaign_id,name,controller_reference) VALUES(%s,'Pilot','p') RETURNING actor_id,public_id",(camp,)).fetchone();c.execute("INSERT INTO actor_characteristic(actor_id,characteristic_rule_id,maximum_value,current_value) SELECT %s,rule_id,7,7 FROM rule_rule WHERE rule_code='characteristic.dexterity'",(aid,));c.execute("INSERT INTO actor_skill SELECT %s,rule_id,1 FROM rule_rule WHERE rule_code='skill.piloting'",(aid,));pkg=c.execute("SELECT content_package_id FROM sys_content_package WHERE package_code='cepheus-engine'").fetchone()[0];item_rule=c.execute("INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status) VALUES(%s,%s,'Test Hull','equipment','approved') RETURNING rule_id",(pkg,'item.test-hull-'+uuid.uuid4().hex)).fetchone()[0];c.execute("INSERT INTO inv_item_definition(rule_id,item_kind,minimum_tech_level,cost_credits) VALUES(%s,'equipment',9,1)",(item_rule,));item=c.execute("INSERT INTO inv_item_instance(campaign_id,item_rule_id,instance_name) VALUES(%s,%s,'Hull') RETURNING item_instance_id",(camp,item_rule)).fetchone()[0];class_rule=c.execute("INSERT INTO rule_rule(content_package_id,rule_code,name,rule_category,rule_status) VALUES(%s,%s,'Test Ship','ship','approved') RETURNING rule_id",(pkg,'ship.test-'+uuid.uuid4().hex)).fetchone()[0];c.execute("INSERT INTO ship_class(ship_class_rule_id,class_code,hull_tons,hull_points,structure_points,minimum_tech_level,construction_cost_minor,maneuver_rating) VALUES(%s,%s,100,2,2,9,1,1)",(class_rule,'test-'+uuid.uuid4().hex));ship,spub=c.execute("INSERT INTO ship_ship(campaign_id,ship_class_rule_id,inventory_item_instance_id,name,hull_current,structure_current) VALUES(%s,%s,%s,'Test',2,2) RETURNING ship_id,public_id",(camp,class_rule,item)).fetchone();position_rule=c.execute("SELECT crew_position_rule_id FROM ship_crew_position_definition WHERE position_code='pilot'").fetchone()[0];position=c.execute("INSERT INTO ship_crew_position(ship_id,campaign_id,crew_position_rule_id,position_identifier) VALUES(%s,%s,%s,'pilot') RETURNING ship_crew_position_id",(ship,camp,position_rule)).fetchone()[0];c.execute("INSERT INTO ship_crew_assignment(ship_crew_position_id,ship_id,campaign_id,actor_id) VALUES(%s,%s,%s,%s)",(position,ship,camp,aid))
    routine=resolve_transport_operation_command(c,initiator_reference='p',idempotency_key='routine',actor_public_id=str(apub),target_public_id=str(spub),target_kind='ship',operation_kind='operate-spacecraft',operation_reference='ordinary cruise',challenging_conditions=False,characteristic_rule_code='characteristic.dexterity',difficulty_rule_code='difficulty.average',random_source=R());self.assertTrue(routine.automatic_success);self.assertIsNone(routine.check_total)
    rough=resolve_transport_operation_command(c,initiator_reference='p',idempotency_key='rough',actor_public_id=str(apub),target_public_id=str(spub),target_kind='ship',operation_kind='operate-spacecraft',operation_reference='rough atmosphere',challenging_conditions=True,characteristic_rule_code='characteristic.dexterity',difficulty_rule_code='difficulty.average',random_source=R());self.assertFalse(rough.automatic_success);self.assertEqual(rough.check_total,9)
