"""Provider-neutral, narration-only referee conversation service."""
from dataclasses import dataclass
from hashlib import sha256
import json
import psycopg
from ai.providers import provider_from_environment
from engine.orchestration import available_tools

@dataclass(frozen=True)
class RefereeTurnResult:
 command_public_id:str;turn_public_id:str;narration:str;replayed:bool

def submit_referee_turn(c:psycopg.Connection,*,initiator_reference:str,idempotency_key:str,campaign_public_id:str,player_text:str,provider=None)->RefereeTurnResult:
 action=player_text.strip()
 if not action:raise ValueError('Player action is required')
 with c.transaction():
  old=c.execute("SELECT command_id,public_id,command_type,command_status FROM cmd_command WHERE initiator_reference=%s AND idempotency_key=%s FOR UPDATE",(initiator_reference,idempotency_key)).fetchone()
  if old:
   if old[2]!='submit_referee_turn':raise ValueError('Idempotency key belongs to another command')
   row=c.execute("SELECT turn.public_id,COALESCE(message.message_text,'') FROM cmd_referee_turn_receipt receipt JOIN camp_referee_turn turn USING(referee_turn_id) LEFT JOIN camp_referee_message message ON message.referee_turn_id=turn.referee_turn_id AND message.speaker_kind='referee' WHERE receipt.command_id=%s",(old[0],)).fetchone()
   return RefereeTurnResult(str(old[1]),str(row[0]),row[1],True)
  campaign=c.execute("SELECT campaign.campaign_id,campaign.name,clock.day_number FROM camp_campaign campaign JOIN camp_clock clock USING(campaign_id) WHERE campaign.public_id=%s AND campaign.owner_reference=%s FOR UPDATE OF campaign,clock",(campaign_public_id,initiator_reference)).fetchone()
  if not campaign:raise PermissionError('Campaign is outside this authority')
  command_id,command_public=c.execute("INSERT INTO cmd_command(command_type,initiator_reference,idempotency_key) VALUES('submit_referee_turn',%s,%s) RETURNING command_id,public_id",(initiator_reference,idempotency_key)).fetchone()
  turn_id,turn_public=c.execute("INSERT INTO camp_referee_turn(campaign_id,campaign_day,turn_status,source_command_id) VALUES(%s,%s,'pending',%s) RETURNING referee_turn_id,public_id",(campaign[0],campaign[2],command_id)).fetchone()
  c.execute("INSERT INTO camp_referee_message(referee_turn_id,campaign_id,message_order,speaker_kind,message_text) VALUES(%s,%s,1,'player',%s)",(turn_id,campaign[0],action));c.execute("INSERT INTO cmd_referee_turn_receipt VALUES(%s,%s,%s)",(command_id,campaign[0],turn_id))
  actors=c.execute("SELECT name FROM actor_actor WHERE campaign_id=%s ORDER BY actor_id LIMIT 20",(campaign[0],)).fetchall()
  actor_states=c.execute("""SELECT actor.name,physical.strength,physical.dexterity,physical.endurance,injury.injury_status FROM actor_actor actor JOIN LATERAL (SELECT max(characteristic.current_value) FILTER(WHERE rule.rule_code='characteristic.strength') AS strength,max(characteristic.current_value) FILTER(WHERE rule.rule_code='characteristic.dexterity') AS dexterity,max(characteristic.current_value) FILTER(WHERE rule.rule_code='characteristic.endurance') AS endurance FROM actor_characteristic characteristic JOIN rule_rule rule ON rule.rule_id=characteristic.characteristic_rule_id WHERE characteristic.actor_id=actor.actor_id) physical ON physical.strength IS NOT NULL AND physical.dexterity IS NOT NULL AND physical.endurance IS NOT NULL LEFT JOIN health_actor_injury_status injury USING(actor_id) WHERE actor.campaign_id=%s ORDER BY actor.actor_id LIMIT 20""",(campaign[0],)).fetchall()
  ships=c.execute("SELECT name FROM ship_ship WHERE campaign_id=%s AND lifecycle_status='active' ORDER BY ship_id LIMIT 20",(campaign[0],)).fetchall()
  ship_states=c.execute("""SELECT ship.name,ship.lifecycle_status,location.name FROM ship_ship ship LEFT JOIN loc_location location ON location.location_id=ship.current_location_id WHERE ship.campaign_id=%s ORDER BY ship.ship_id LIMIT 20""",(campaign[0],)).fetchall()
  journey_states=c.execute("""SELECT journey.name,ship.name,journey.journey_status,origin.name,destination.name,leg.leg_status FROM journey_journey journey JOIN ship_ship ship USING(ship_id) LEFT JOIN journey_leg leg ON leg.journey_id=journey.journey_id AND leg.leg_order=1 LEFT JOIN loc_location origin ON origin.location_id=leg.origin_location_id LEFT JOIN loc_location destination ON destination.location_id=leg.destination_location_id WHERE journey.campaign_id=%s ORDER BY journey.created_at DESC LIMIT 12""",(campaign[0],)).fetchall()
  trading_accounts=c.execute("""SELECT actor.name,ship.name,balance.balance_minor,account.currency_code FROM cmd_trading_preparation_receipt setup JOIN actor_actor actor USING(actor_id) JOIN ship_ship ship USING(ship_id) JOIN fin_account account ON account.account_id=setup.trader_account_id JOIN fin_account_balance balance ON balance.account_id=account.account_id WHERE setup.campaign_id=%s ORDER BY setup.command_id DESC LIMIT 12""",(campaign[0],)).fetchall()
  cargo_states=c.execute("""SELECT ship.name,rule.name,sum(placement.quantity) FROM cmd_trading_preparation_receipt setup JOIN ship_ship ship USING(ship_id) JOIN inv_container_lot placement ON placement.container_id=setup.cargo_container_id JOIN inv_lot lot USING(lot_id) JOIN rule_rule rule ON rule.rule_id=lot.item_rule_id WHERE setup.campaign_id=%s AND lot.lot_status='active' GROUP BY ship.ship_id,ship.name,lot.item_rule_id,rule.name ORDER BY ship.name,rule.name LIMIT 30""",(campaign[0],)).fetchall()
  encounter_states=c.execute("""SELECT encounter.public_id::text,type.encounter_type_code,encounter.current_mode,combat.current_round,combat.combat_status FROM enc_encounter encounter JOIN rule_encounter_type type ON type.rule_id=encounter.encounter_type_rule_id LEFT JOIN enc_personal_combat combat USING(encounter_id) WHERE encounter.campaign_id=%s AND encounter.encounter_status='active' ORDER BY encounter.created_at DESC LIMIT 8""",(campaign[0],)).fetchall()
  encounter_participants=c.execute("""SELECT encounter.public_id::text,actor.name,participant.participant_role,participant.side_code,participant.aware,attitude_rule.name FROM enc_encounter encounter JOIN enc_participant participant USING(encounter_id) JOIN actor_actor actor USING(actor_id) LEFT JOIN enc_attitude_state attitude USING(encounter_id,actor_id) LEFT JOIN rule_rule attitude_rule ON attitude_rule.rule_id=attitude.attitude_rule_id WHERE encounter.campaign_id=%s AND encounter.encounter_status='active' ORDER BY encounter.created_at DESC,participant.joined_at LIMIT 40""",(campaign[0],)).fetchall()
  memories=c.execute("SELECT title,note_text FROM camp_journal_note WHERE campaign_id=%s AND ai_memory_enabled ORDER BY created_at DESC LIMIT 8",(campaign[0],)).fetchall()
  history=c.execute("SELECT message.speaker_kind,message.message_text FROM camp_referee_message message JOIN camp_referee_turn turn USING(referee_turn_id,campaign_id) WHERE message.campaign_id=%s AND turn.turn_status='completed' ORDER BY message.referee_message_id DESC LIMIT 12",(campaign[0],)).fetchall()[::-1]
  sources=c.execute("SELECT page.source_document_id,page.page_number,page.text_content FROM camp_source_page page JOIN camp_source_document document USING(source_document_id,campaign_id) WHERE page.campaign_id=%s AND page.review_status='verified' AND page.search_document @@ websearch_to_tsquery('english',%s) ORDER BY ts_rank(page.search_document,websearch_to_tsquery('english',%s)) DESC LIMIT 6",(campaign[0],action,action)).fetchall()
  combat_facts=c.execute("""SELECT attacker.name,target.name,weapon.name,receipt.hit,receipt.attack_total,receipt.target_number,receipt.effect,receipt.raw_damage,receipt.armor_rating,receipt.penetrating_damage,damage.allocation_status,attack.resolved_at FROM cmd_attack_receipt receipt JOIN enc_personal_attack attack ON attack.personal_attack_id=receipt.personal_attack_id JOIN enc_encounter encounter ON encounter.encounter_id=attack.encounter_id JOIN actor_actor attacker ON attacker.actor_id=attack.attacker_actor_id JOIN actor_actor target ON target.actor_id=attack.target_actor_id JOIN rule_rule weapon ON weapon.rule_id=attack.weapon_rule_id LEFT JOIN health_damage_instance damage ON damage.attack_command_id=receipt.command_id WHERE encounter.campaign_id=%s ORDER BY attack.resolved_at DESC NULLS LAST LIMIT 12""",(campaign[0],)).fetchall()
  for order,row in enumerate(sources,1):c.execute("INSERT INTO camp_referee_source_context VALUES(%s,%s,%s,%s)",(turn_id,row[0],row[1],order))
 context=f"Campaign: {campaign[1]}; day {campaign[2]}. Active characters: {', '.join(x[0] for x in actors) or 'none'}. Active ships: {', '.join(x[0] for x in ships) or 'none'}."
 if actor_states:context+='\nAuthoritative current character state:\n'+'\n'.join(f'- {name}: STR {strength}, DEX {dexterity}, END {endurance}; {injury or "uninjured"}' for name,strength,dexterity,endurance,injury in actor_states)
 if ship_states:context+='\nAuthoritative current ship state:\n'+'\n'.join(f'- {name}: {status}; location {location or "in transit or unknown"}' for name,status,location in ship_states)
 if journey_states:context+='\nAuthoritative journey state:\n'+'\n'.join(f'- {name} ({ship}): {status}; {origin or "unknown origin"} to {destination or "unknown destination"}; first leg {leg_status or "not prepared"}' for name,ship,status,origin,destination,leg_status in journey_states)
 if trading_accounts:context+='\nAuthoritative trading balances (minor currency units):\n'+'\n'.join(f'- {actor}, trading through {ship}: {balance} {currency}' for actor,ship,balance,currency in trading_accounts)
 if cargo_states:context+='\nAuthoritative active cargo:\n'+'\n'.join(f'- {ship}: {quantity} tons of {good}' for ship,good,quantity in cargo_states)
 if encounter_states:context+='\nAuthoritative active encounters:\n'+'\n'.join(f'- Encounter {public_id}: {kind}; mode {mode}'+(f'; combat round {round_number}, {combat_status}' if round_number is not None else '') for public_id,kind,mode,round_number,combat_status in encounter_states)
 if encounter_participants:context+='\nAuthoritative active encounter participants:\n'+'\n'.join(f'- Encounter {public_id}: {name}, {role}, side {side}, '+('aware' if aware else 'unaware' if aware is not None else 'awareness unknown')+(f', attitude {attitude}' if attitude else '') for public_id,name,role,side,aware,attitude in encounter_participants)
 if combat_facts:
  context+='\nRecent committed combat facts (narrate as resolved; never recalculate):\n'+'\n'.join(f'- {attacker} attacked {target} with {weapon}: {"HIT" if hit else "MISS"} ({total} vs {target_number}, Effect {effect}); raw damage {raw}, armor {armor}, penetrating damage {penetrating}'+(f'; wound allocation {allocation}' if allocation else '')+f'; resolved {resolved.isoformat()}.' for attacker,target,weapon,hit,total,target_number,effect,raw,armor,penetrating,allocation,resolved in combat_facts)
 if memories:context+='\nApproved memory:\n'+'\n'.join(f'- {x[0]}: {x[1]}' for x in memories)
 if sources:context+='\nPrivate verified source excerpts (never reveal secrets unless the player action has earned them):\n'+'\n'.join(f'[Source page {x[1]}]\n{x[2]}' for x in sources)
 specs={spec.name:spec for spec in available_tools()};catalog='\n'.join(f"{spec.name}: {spec.description}; required={','.join(spec.required_arguments)}; optional={','.join(spec.optional_arguments)}" for spec in specs.values())
 messages=[{'role':'system','content':'You are the Emporos referee. Return JSON exactly as {"narration":"concise grounded prose","tool_request":null} or with tool_request {"name":"allowlisted_name","summary":"player-visible action","arguments":{"argument":scalar}}. Never invent, alter, or recalculate a mechanic, roll, money, inventory, damage, time, travel, or position. You may narrate committed mechanical facts explicitly supplied as authoritative state, without contradicting them. A proposed tool is not yet executed. Propose at most one tool and only when the player clearly requested that action and every required argument is known from supplied state. Never mention hidden source text or page numbers.\nALLOWLIST:\n'+catalog},{'role':'system','content':context}]
 messages.extend({'role':'assistant' if role=='referee' else 'user','content':text} for role,text in history);messages.append({'role':'user','content':action})
 client=provider or provider_from_environment();input_hash=sha256(repr(messages).encode()).hexdigest()
 with c.transaction():invocation=c.execute("INSERT INTO ai_model_invocation(campaign_id,provider_code,model_name,purpose_code,input_sha256,invocation_status,source_command_id) VALUES(%s,%s,%s,'referee_narration',%s,'pending',%s) RETURNING model_invocation_id",(campaign[0],client.provider_code,client.model,input_hash,command_id)).fetchone()[0]
 try:
  result=client.chat(messages=messages,json_output=True,max_tokens=700);payload=json.loads(result.content);narration=str(payload.get('narration','')).strip();proposal=payload.get('tool_request')
  if not narration:raise RuntimeError('AI referee returned empty narration')
  if proposal is not None:
   if not isinstance(proposal,dict) or proposal.get('name') not in specs or not isinstance(proposal.get('arguments'),dict):raise RuntimeError('AI referee proposed an invalid tool request')
   spec=specs[proposal['name']];arguments=proposal['arguments'];allowed=set(spec.required_arguments)|set(spec.optional_arguments)
   if set(spec.required_arguments)-set(arguments) or set(arguments)-allowed:raise RuntimeError('AI referee proposed invalid tool arguments')
   if any(isinstance(value,(dict,list)) for value in arguments.values()):raise RuntimeError('AI referee tool arguments must be scalar')
 except Exception as exc:
  with c.transaction():c.execute("UPDATE ai_model_invocation SET invocation_status='failed',error_code=%s,completed_at=clock_timestamp() WHERE model_invocation_id=%s",(exc.__class__.__name__,invocation));c.execute("UPDATE camp_referee_turn SET turn_status='failed',failure_code=%s,completed_at=clock_timestamp() WHERE referee_turn_id=%s",(exc.__class__.__name__,turn_id));c.execute("UPDATE cmd_command SET command_status='failed',completed_at=clock_timestamp() WHERE command_id=%s",(command_id,))
  raise
 with c.transaction():
  c.execute("INSERT INTO camp_referee_message(referee_turn_id,campaign_id,message_order,speaker_kind,message_text) VALUES(%s,%s,2,'referee',%s)",(turn_id,campaign[0],narration));c.execute("UPDATE camp_referee_turn SET turn_status='completed',completed_at=clock_timestamp() WHERE referee_turn_id=%s",(turn_id,));c.execute("UPDATE ai_model_invocation SET provider_code=%s,model_name=%s,output_sha256=%s,invocation_status='completed',prompt_tokens=%s,completion_tokens=%s,completed_at=clock_timestamp() WHERE model_invocation_id=%s",(result.provider,result.model,sha256(narration.encode()).hexdigest(),result.prompt_tokens,result.completion_tokens,invocation));c.execute("INSERT INTO cmd_domain_event(command_id,event_order,event_type) VALUES(%s,1,'referee_turn_completed')",(command_id,));c.execute("UPDATE cmd_command SET command_status='completed',completed_at=clock_timestamp() WHERE command_id=%s",(command_id,))
  if proposal is not None:
   summary=str(proposal.get('summary') or specs[proposal['name']].description).strip();request_id=c.execute("INSERT INTO camp_referee_tool_request(referee_turn_id,campaign_id,tool_name,request_summary,request_status) VALUES(%s,%s,%s,%s,'proposed') RETURNING referee_tool_request_id",(turn_id,campaign[0],proposal['name'],summary)).fetchone()[0]
   for order,(name,value) in enumerate(arguments.items(),1):
    kind='null' if value is None else 'boolean' if isinstance(value,bool) else 'integer' if isinstance(value,int) else 'number' if isinstance(value,float) else 'string';c.execute("INSERT INTO camp_referee_tool_argument VALUES(%s,%s,%s,%s,%s)",(request_id,name,'' if value is None else str(value).lower() if isinstance(value,bool) else str(value),kind,order))
 return RefereeTurnResult(str(command_public),str(turn_public),narration,False)
